In [ ]:
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct # These are the different types of distance metrics that can be used for vector search, and the structure of a point in the vector database.
# Distance: This is a class that defines the different types of distance metrics that can be used for vector search, such as cosine similarity, Euclidean distance, etc, for the VECTOR DATABASE.
# VectorParams: This is a class that defines the parameters for the vector database, such as embedding size and distance metric , for the VECTOR DATABASE.
# PointStruct: This is a class that defines the structure of a point in the vector database, which includes an id, a vector, and optional payload data; i.e. metadata, 

import openai

### Read the sampled dataset with Amazon inventory data

In [4]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [5]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,"MUQI Bluetooth Speaker, Portable Bluetooth Spe...",4.4,113,[IPX7 Waterproof Bluetooth Speaker: The silico...,[],15.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Powerful sound, compact size, and ...",MUQI,"[Electronics, Portable Audio & Video, Portable...","{'Product Dimensions': '6.9 x 2 x 2.6 inches',...",B0B3WPPBZ8,NaN,NaN,NaN
1,All Electronics,DEEBOX Wireless Gaming Headsets with Mic for P...,4.6,642,[✅【Focused Voice Pickup】In-built mic cancels b...,[],59.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Wireless Gaming Headset', 'url': '...",DEEBOX,[],{'Package Dimensions': '8.11 x 6.97 x 4.57 inc...,B0C8J2CCKV,NaN,NaN,NaN
2,Computers,"USB Flash Drive 1TB, Portable Thumb Drive 1000...",4.1,229,[Ultra Large Capacity USB Drive - USB Flash Dr...,[Manage and organize all your most important d...,19.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Amazing Value USB Memory Stick Va...,NOOYU,"[Electronics, Computers & Accessories, Data St...","{'Brand': 'NOOYU', 'Item Weight': '0.563 ounce...",B0C6FDCK21,NaN,NaN,NaN
3,Camera & Photo,"REOLINK PTZ Camera Outdoor, 5MP HD WiFi Camera...",3.9,128,[5MP HD & 3X OPTICAL ZOOM: With the resolution...,[],109.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Reolink Trackmix WIFI and PoE Revi...,REOLINK,"[Electronics, Camera & Photo, Video Surveillan...",{'Product Dimensions': '4.65 x 3.35 x 3.35 inc...,B0B61FHY76,NaN,NaN,NaN
4,Camera & Photo,Merkury Innovations Indoor Smart Security Came...,4.2,416,[SMART SECURITY: The Merkury Innovations Smart...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Much easier to set up than the oth...,Merkury Innovations,"[Electronics, Camera & Photo, Video Surveillan...",{'Product Dimensions': '3.54 x 3.45 x 5.91 inc...,B0B4RBPQKB,NaN,NaN,NaN

In [6]:
list(df_items["features"].items())[0]

(0,
 ['IPX7 Waterproof Bluetooth Speaker: The silicone case and closed port cover of this waterproof bluetooth speaker provide strong waterproof & dustproof protection, even submerged in water; can be used in bathroom, beach, swimming pool without worrying about rain or spills, it is an excellent shower speaker, hiking speaker, camping speaker,car speaker.',
  'Clear and Loud Stereo: This wireless stereo speaker has 2 built-in drivers to provide 10w audio power for loud and clear sound; TWS technology allows you to pair two portable bluetooth speakers with your phone, dual pairing to enjoy true wireless stereo.If you want to rock, get this! You will be happy!',
  'Long battery life: This portable bluetooth speaker is equipped with a 2200mAh Li-ion battery, which only takes 3 hours to charge and can play for 24 hours at 50% volume, making it easy to use and play all day.MUQI wireless Bluetooth portable small speakers, carnival party to add atmosphere essential items, high-quality sound quality and super battery life for your party plus points.',
  'Powerful Bluetooth 5.0 technology: This wireless bluetooth speaker can quickly connect with your phone with in a range of 66ft without worrying about disconnection, providing clear and stable sound whether indoors or outdoors.This portable small speakers can also be paired with each other, a pair of MUQI Bluetooth small speakers stereo surround sound will make you very amazing！',
  'Classic features: This wireless speaker has a built-in microphone for making calls; it is equipped with a carabiner, which can be hung on a backpack when hiking outdoors; AUX jack, which can be connected to some computers or TVs without bluetooth function. It is the preferred bluetooth speaker for home, party, outdoor or travel.'])

In [7]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51Kn6oexQkL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51Kn6oexQkL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/81gDfqCHSeL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/512U86nKD8L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/512U86nKD8L._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/71YLvhZhGLL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41QcjmISEJL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41QcjmISEJL._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/61LVJjp6VrL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41BT1cSQw5L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41BT1cSQw5L._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71b2+xvdftL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41zIl0iC-7L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41zIl0iC-7L._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/61a3p-+2mkL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41MvmtcJ0LL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41MvmtcJ0LL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/612HlfP0oJL._AC_SL1500_.jpg'}])

### Preprocessing title and features

In [8]:
# New string - Description combining title and features

def preprocess_description(row):
    return f"{row['title']}{' '.join(row['features'])}"

In [9]:
def extract_first_large_image(row):
    return row['images'][0].get("large", "") # Extract the 'large' image URL from the first image dictionary if available, else return an empty string

In [11]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)

In [12]:
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [13]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,All Electronics,"MUQI Bluetooth Speaker, Portable Bluetooth Spe...",4.4,113,[IPX7 Waterproof Bluetooth Speaker: The silico...,"MUQI Bluetooth Speaker, Portable Bluetooth Spe...",15.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Powerful sound, compact size, and ...",MUQI,"[Electronics, Portable Audio & Video, Portable...","{'Product Dimensions': '6.9 x 2 x 2.6 inches',...",B0B3WPPBZ8,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51Kn6oexQk...
1,All Electronics,DEEBOX Wireless Gaming Headsets with Mic for P...,4.6,642,[✅【Focused Voice Pickup】In-built mic cancels b...,DEEBOX Wireless Gaming Headsets with Mic for P...,59.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Wireless Gaming Headset', 'url': '...",DEEBOX,[],{'Package Dimensions': '8.11 x 6.97 x 4.57 inc...,B0C8J2CCKV,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41we2iBE2P...
2,Computers,"USB Flash Drive 1TB, Portable Thumb Drive 1000...",4.1,229,[Ultra Large Capacity USB Drive - USB Flash Dr...,"USB Flash Drive 1TB, Portable Thumb Drive 1000...",19.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Amazing Value USB Memory Stick Va...,NOOYU,"[Electronics, Computers & Accessories, Data St...","{'Brand': 'NOOYU', 'Item Weight': '0.563 ounce...",B0C6FDCK21,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31mOkS1N93...
3,Camera & Photo,"REOLINK PTZ Camera Outdoor, 5MP HD WiFi Camera...",3.9,128,[5MP HD & 3X OPTICAL ZOOM: With the resolution...,"REOLINK PTZ Camera Outdoor, 5MP HD WiFi Camera...",109.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Reolink Trackmix WIFI and PoE Revi...,REOLINK,"[Electronics, Camera & Photo, Video Surveillan...",{'Product Dimensions': '4.65 x 3.35 x 3.35 inc...,B0B61FHY76,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31m6CwBLCQ...
4,Camera & Photo,Merkury Innovations Indoor Smart Security Came...,4.2,416,[SMART SECURITY: The Merkury Innovations Smart...,Merkury Innovations Indoor Smart Security Came...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Much easier to set up than the oth...,Merkury Innovations,"[Electronics, Camera & Photo, Video Surveillan...",{'Product Dimensions': '3.54 x 3.45 x 5.91 inc...,B0B4RBPQKB,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41mFtR5t1W...

### Sample 50 Itemd from the dataset

In [14]:
df_sample = df_items.sample(50, random_state=42)
len(df_sample)

50

In [15]:
data_to_embed = df_sample[["description", "image", "rating_number", "price", "average_rating", "parent_asin"]].to_dict(orient="records")

In [16]:
data_to_embed[0:2]

# Here we have a list of dictionaries which can each be indiv processed for embedding and storage in Qdrant; our vector DB

[{'description': 'COOLHOOD 15.6 Inch Portable Monitor, Ultra Slim&Light Portable Laptop Monitor (15.6")',
  'image': 'https://m.media-amazon.com/images/I/51uWC9HIORL._AC_.jpg',
  'rating_number': 111,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B0BGMY79D5'},
 {'description': 'Google Nest Cam Outdoor or Indoor, Battery - 2nd Generation - 1 PackNest Cam has built-in intelligence and can tell the difference between a person, animal, and vehicle and send alerts directly through the Google Home app[1], no subscription required.Controller Type:Google Assistant.Connectivity protocol:Bluetooth;Wi-Fi.Power source type:Battery Powered Easily check in from anywhere 24/7 with 1080p HDR video[1] with night vision, and see what you missed with 3 hours of free event video history[2]; add a Nest Aware subscription (sold separately) for up to 60 days of video history[3] If your Wi-Fi goes down or there’s a power outage, Nest Cam will store up to an hour of recorded events so you can see what you missed[4]. Nest Cam Outdoor comes with a wall plate that can be mounted on your brick wall. Put Nest Cam anywhere, outside or in; it’s battery powered, so you don’t need to set it up near an outlet, and the magnetic mount makes installation effortless For continuous power and 24/7 video recording with Nest Aware Plus, add a weatherproof power cable or indoor stand with power cable (both sold separately) Stream your live video feed hands-free on compatible smart displays with Google Assistant, and compatible smart displays, smart TVs, and tablets with Amazon Alexa Nest Cam requires the Google Home app and a free Google Account; it’s not compatible with the Nest app or the Nest site Set up Activity Zones to receive phone notifications about specific areas of your home and know when familiar faces arrive[1,5] Take action in an instant if something happens; talk and listen with the built-in speaker and mic on your security camera or call your local emergency service directly from the Google Home app (Nest Aware subscription required)[6] Please refer to the product description section below for all applicable legal disclaimers denoted by the bracketed numbers in the preceding bullet points (e.g., [1], [2], etc.). Up to 6.10 m (20 ft) illumination. 6 high-power 850 nm infrared LEDs',
  'image': 'https://m.media-amazon.com/images/I/21m2TKRIr2L._AC_.jpg',
  'rating_number': 2995,
  'price': 163.99,
  'average_rating': 4.2,
  'parent_asin': 'B0BWFJ31C5'}]

### Embedding our data - Defining our embedding function

In [17]:
# OpenAI embedding example -  
# this embedding algorithm ; A deep transformer model trained to minimise semantic distance between related texts and maximise distance between unrelated ones.

response = openai.embeddings.create( 
    input="This is a sample description for embedding.",
    model="text-embedding-3-small"
)   

response.data[0].embedding

[-0.00025012617697939277,
 0.02688148431479931,
 0.022186147049069405,
 0.0020576417446136475,
 0.0012210275745019317,
 -0.038990508764982224,
 0.02740318700671196,
 -0.017531998455524445,
 -0.00655219005420804,
 0.028556426987051964,
 0.01587078347802162,
 -0.012953360565006733,
 0.022350896149873734,
 -0.04437229409813881,
 0.0023699775338172913,
 0.011216634884476662,
 -0.005395517218858004,
 0.043136682361364365,
 0.0036519276909530163,
 0.06859034299850464,
 0.021238842979073524,
 -0.027609122917056084,
 -0.019412878900766373,
 0.06507570296525955,
 0.005525943357497454,
 -0.04818897321820259,
 -0.004527154844254255,
 0.03783726692199707,
 0.07501553744077682,
 -0.0011214918922632933,
 0.023119723424315453,
 -0.04091257601976395,
 0.011834442615509033,
 -0.024163130670785904,
 -0.007550978567451239,
 0.022460728883743286,
 0.04643165320158005,
 0.006600241642445326,
 -0.0025295778177678585,
 -0.0022120934445410967,
 0.016227738931775093,
 -0.042862098664045334,
 -0.004310922231525183,
 0.039429835975170135,
 0.000957601354457438,
 0.05022087320685387,
 -0.05947425216436386,
 -0.041077323257923126,
 0.005858873017132282,
 0.05066020041704178,
 -0.03742539510130882,
 -0.04439975321292877,
 -0.0381118468940258,
 -0.006782151758670807,
 -0.030807992443442345,
 0.009733897633850574,
 -0.013179889880120754,
 0.05755218490958214,
 -0.013324044644832611,
 0.0022790227085351944,
 0.0124934371560812,
 -0.007907933555543423,
 -0.01731233485043049,
 0.024492628872394562,
 -0.009795678779482841,
 0.010200685821473598,
 -0.05060528591275215,
 0.03410296514630318,
 -0.026222489774227142,
 0.011772661469876766,
 0.0878659337759018,
 0.002474661683663726,
 -0.03948475420475006,
 0.01529416348785162,
 0.03410296514630318,
 0.0030667269602417946,
 -0.07984816282987595,
 0.004293760750442743,
 0.004534019157290459,
 -0.028062181547284126,
 -0.008587521500885487,
 0.019261859357357025,
 -0.04195598140358925,
 -0.013921258971095085,
 -0.037178270518779755,
 0.023229556158185005,
 -0.0660092830657959,
 0.00698122289031744,
 -0.03138461336493492,
 0.003535230876877904,
 -0.04173631593585014,
 -0.038578636944293976,
 -0.04129698872566223,
 -0.033910758793354034,
 0.03432263061404228,
 0.031769026070833206,
 -0.05022087320685387,
 -0.02465737611055374,
 -0.007763778790831566,
 0.021431049332022667,
 0.02896829880774021,
 -0.03316938877105713,
 -0.029709668830037117,
 -0.04242277145385742,
 0.021678172051906586,
 -0.07084190845489502,
 0.014607710763812065,
 -0.002210377249866724,
 -0.049506962299346924,
 -0.02541247569024563,
 -0.04058307781815529,
 -0.004935594275593758,
 -0.003379062982276082,
 0.046843525022268295,
 0.019097110256552696,
 -0.011347061023116112,
 0.01162850670516491,
 0.007029274478554726,
 -0.04547061771154404,
 -0.022186147049069405,
 -0.05247243493795395,
 -0.032180897891521454,
 0.034075506031513214,
 -0.03923762962222099,
 0.0019392286194488406,
 -0.05472400039434433,
 0.016062989830970764,
 0.0012870986247435212,
 -0.03871592506766319,
 -0.013042598962783813,
 -0.0030529978685081005,
 -0.011958003975450993,
 -0.02302362024784088,
 0.011999191716313362,
 -0.05077003315091133,
 -0.02325701341032982,
 -0.03599757328629494,
 0.009830000810325146,
 -0.020030686631798744,
 0.008457096293568611,
 0.005622046533972025,
 -0.035887740552425385,
 0.052527353167533875,
 0.010221279226243496,
 -0.01793014258146286,
 0.012342417612671852,
 -0.03794709965586662,
 0.04126952961087227,
 0.013880071230232716,
 -0.016131635755300522,
 -0.021568341180682182,
 0.007214616518467665,
 -0.08484554290771484,
 -0.00040736672235652804,
 -0.03487179055809975,
 -0.018410658463835716,
 0.008038359694182873,
 -0.024780938401818275,
 -0.013989903964102268,
 0.002606803784146905,
 0.005725014489144087,
 0.012047243304550648,
 0.03130223974585533,
 -0.0028933975845575333,
 -0.05777185037732124,
 -0.020579848438501358,
 0.01775166392326355,
 -0.011491216719150543,
 -0.04566282778978348,
 -0.0008576366817578673,
 -0.015788409858942032,
 -0.016955379396677017,
 -0.02662063203752041,
 0.035887740552425385,
 -0.0010537047637626529,
 0.012740559875965118,
 0.011793255805969238,
 -0.06326346844434738,
 0.049342211335897446,
 0.0018122348701581359,
 -0.0024437711108475924,
 0.059858664870262146,
 -0.0006049363291822374,
 0.02430042251944542,
 -0.009830000810325146,
 0.009157277643680573,
 0.007324449252337217,
 0.034597210586071014,
 0.049452044069767,
 -0.010701796039938927,
 -0.013207348063588142,
 -0.009287703782320023,
 0.019769834354519844,
 -0.020744597539305687,
 -0.04500383138656616,
 -0.002445487305521965,
 0.03981424868106842,
 0.004736522678285837,
 0.05628911405801773,
 -0.030094081535935402,
 0.01434685941785574,
 0.043905507773160934,
 -0.00991237536072731,
 0.027430646121501923,
 -0.016474861651659012,
 0.014992124401032925,
 -0.02423177659511566,
 -0.051840901374816895,
 -0.016969108954072,
 -0.016090448945760727,
 0.011257822625339031,
 -0.002299616113305092,
 0.032784976065158844,
 -0.01731233485043049,
 -0.030780533328652382,
 0.034432463347911835,
 -0.006840500049293041,
 -0.024753481149673462,
 -0.01042721513658762,
 -0.035036541521549225,
 -0.03025883063673973,
 0.05930950492620468,
 0.05661860853433609,
 -0.001590853906236589,
 -0.06024307757616043,
 0.02386109158396721,
 -0.03728810325264931,
 -0.01939914934337139,
 -0.004870381206274033,
 -0.017902683466672897,
 0.024423982948064804,
 -0.011230364441871643,
 -0.0031010496895760298,
 -0.05326871946454048,
 0.0023768420796841383,
 0.042862098664045334,
 -0.04593740776181221,
 -0.015390266664326191,
 -0.012740559875965118,
 -0.005628911312669516,
 -0.03369109332561493,
 0.006318795960396528,
 0.024492628872394562,
 -0.017806580290198326,
 0.009342620149254799,
 -0.005306278355419636,
 0.005337168928235769,
 -0.08023257553577423,
 -0.0025055520236492157,
 0.018410658463835716,
 0.02268039435148239,
 0.03901796415448189,
 -0.007660810835659504,
 -0.02137613296508789,
 -0.004410457797348499,
 -0.006689480505883694,
 -0.03437754511833191,
 0.026167573407292366,
 0.02309226430952549,
 -0.025975365191698074,
 -0.03067070245742798,
 -0.024698564782738686,
 -0.0378921814262867,
 0.0005852008471265435,
 0.005532807670533657,
 -0.01382515486329794,
 0.025618409737944603,
 0.001004794961772859,
 0.008285482414066792,
 -0.03489924967288971,
 -0.006909145507961512,
 -0.03426771238446236,
 0.037095896899700165,
 0.0036553600803017616,
 -0.05085240676999092,
 0.010543911717832088,
 -0.03130223974585533,
 -0.02791116200387478,
 -0.008038359694182873,
 0.028913382440805435,
 -0.032345645129680634,
 -0.04612961411476135,
 0.00991237536072731,
 0.03794709965586662,
 -0.03888067603111267,
 -0.011278416030108929,
 0.03187885880470276,
 -0.013866342604160309,
 -0.005004239268600941,
 0.015074498951435089,
 0.008992528542876244,
 -0.015527557581663132,
 0.047886934131383896,
 -0.016969108954072,
 -0.042971931397914886,
 0.02008560299873352,
 0.018740154802799225,
 0.026263676583766937,
 0.06562487035989761,
 -0.009514233097434044,
 0.011141125112771988,
 -0.0012047243071720004,
 0.011299009434878826,
 0.03152190148830414,
 0.015843326225876808,
 0.02423177659511566,
 0.00882778037339449,
 -0.031412068754434586,
 0.08479062467813492,
 -0.040390871465206146,
 0.014401775784790516,
 -0.02016797661781311,
 -0.035805366933345795,
 0.043383803218603134,
 -0.020181706175208092,
 -0.012211991474032402,
 0.06556995213031769,
 0.004314354620873928,
 -0.014552795328199863,
 -0.00024647937971167266,
 0.04343872144818306,
 -0.008820915594696999,
 0.02387482114136219,
 -0.07215989381074905,
 -0.0020130223128944635,
 0.004832626320421696,
 -0.025659598410129547,
 0.02646961249411106,
 0.02136240527033806,
 -0.011566726490855217,
 0.0295723769813776,
 -0.05145648494362831,
 0.024588732048869133,
 -0.01175893284380436,
 0.031164947897195816,
 -0.05422975495457649,
 -0.0073038553819060326,
 0.005347465630620718,
 0.020483745262026787,
 0.0381118468940258,
 -0.05991358309984207,
 -0.04017120599746704,
 0.007832423783838749,
 -0.004956187680363655,
 -0.024877041578292847,
 0.037617601454257965,
 -0.04901271313428879,
 0.03404804691672325,
 0.033059556037187576,
 -0.04121461510658264,
 -0.015513828955590725,
 -0.007228345610201359,
 0.0010322530288249254,
 0.01930304616689682,
 0.04423500597476959,
 -0.05738743767142296,
 0.039265088737010956,
 -0.06084715574979782,
 -0.02241954207420349,
 -0.03465212509036064,
 -0.0232707429677248,
 0.048298805952072144,
 0.018479304388165474,
 0.017257418483495712,
 -0.027622852474451065,
 -0.00575590506196022,
 -0.02033272571861744,
 -0.03248293697834015,
 0.028474053367972374,
 0.024945687502622604,
 0.008113869465887547,
 0.04720047861337662,
 -0.027636582031846046,
 0.0038338378071784973,
 -0.04385059326887131,
 0.017339792102575302,
 0.01912456937134266,
 0.010674337856471539,
 0.004393296781927347,
 -0.014291943050920963,
 -0.005306278355419636,
 0.001922067254781723,
 -0.018163535743951797,
 -0.032263271510601044,
 0.02093680389225483,
 -0.007180294021964073,
 0.029764585196971893,
 0.02059357799589634,
 -0.04113223776221275,
 -0.006160912103950977,
 -0.0075235203839838505,
 -0.013324044644832611,
 0.02885846607387066,
 -0.0004526296688709408,
 0.01998949982225895,
 0.030396120622754097,
 0.0295723769813776,
 -9.578158642398193e-05,
 -0.002591358497738838,
 -0.02351786568760872,
 -0.018136076629161835,
 -0.059584084898233414,
 0.00784615334123373,
 0.026318592950701714,
 -0.03067070245742798,
 -0.013934987597167492,
 0.034597210586071014,
 -0.007097919937223196,
 0.011134261265397072,
 -0.00930143240839243,
 -0.018561678007245064,
 -0.03470704331994057,
 0.023504136130213737,
 -0.025989094749093056,
 -0.0005294265574775636,
 0.025645868852734566,
 -0.004588935524225235,
 -0.0122325848788023,
 0.022103773429989815,
 0.025467390194535255,
 -0.004262870643287897,
 -0.022103773429989815,
 -0.000879517407156527,
 0.007276397664099932,
 0.04272481054067612,
 -0.002593074692413211,
 0.04431737959384918,
 -0.03325176239013672,
 -0.0020233190152794123,
 -0.05672844126820564,
 -0.01258267555385828,
 0.0042663030326366425,
 0.02861134335398674,
 0.017888953909277916,
 -0.011326467618346214,
 -0.012452250346541405,
 0.015884513035416603,
 -0.023229556158185005,
 0.015266705304384232,
 -0.002424893667921424,
 -0.028309304267168045,
 -0.009473045356571674,
 -0.03613486513495445,
 -0.031686652451753616,
 -0.04486653953790665,
 -0.02740318700671196,
 -0.0058382791467010975,
 0.012994547374546528,
 -0.008868967182934284,
 -0.019605085253715515,
 -0.008992528542876244,
 -0.013179889880120754,
 -0.006404602434486151,
 0.01750454120337963,
 0.05576740950345993,
 -0.009164142422378063,
 0.004544316325336695,
 0.031082572415471077,
 0.04220310598611832,
 0.004039773717522621,
 0.030560869723558426,
 0.027265897020697594,
 -0.005223904270678759,
 0.07062224298715591,
 -0.012424792163074017,
 -0.0475848950445652,
 -0.01434685941785574,
 -0.015637390315532684,
 0.03025883063673973,
 -0.03179648518562317,
 0.015747223049402237,
 -0.002660003723576665,
 0.018849987536668777,
 0.03426771238446236,
 -0.017710477113723755,
 -0.04846355319023132,
 0.019248129799962044,
 -0.06326346844434738,
 -0.006298202555626631,
 -0.006236421875655651,
 0.013591761700809002,
 0.012266907840967178,
 -0.07792609930038452,
 0.010736118070781231,
 0.0193167757242918,
 0.1162026971578598,
 0.02232343889772892,
 -0.010029071941971779,
 0.04439975321292877,
 -0.025810617953538895,
 -0.020209163427352905,
 -0.0073038553819060326,
 0.0067787193693220615,
 -0.01555501576513052,
 -0.0003438698477111757,
 -0.01602180302143097,
 -0.0244651697576046,
 -0.04659640043973923,
 0.04110478237271309,
 -0.0011086208978667855,
 -0.002224106341600418,
 0.028638802468776703,
 0.00446194177493453,
 0.0539277158677578,
 0.02171936072409153,
 -0.012864121235907078,
 -0.04439975321292877,
 0.019948313012719154,
 -0.02266666479408741,
 0.03264768421649933,
 -0.03223581239581108,
 -0.0013480213237926364,
 0.007448010612279177,
 0.019962040707468987,
 0.019948313012719154,
 0.0008271753904409707,
 -0.036244697868824005,
 0.03146698698401451,
 -0.004750251770019531,
 -0.02265293523669243,
 -0.013042598962783813,
 0.03143952786922455,
 -0.0030615786090493202,
 -0.03487179055809975,
 0.008347263559699059,
 -0.0028865330386906862,
 -0.024767208844423294,
 -0.07265414297580719,
 0.008978799916803837,
 -0.025961637496948242,
 -0.04094003140926361,
 -0.004832626320421696,
 0.019632544368505478,
 0.03827659785747528,
 -0.05590469762682915,
 -0.0008113011717796326,
 -0.0037445989437401295,
 0.04912254586815834,
 0.036244697868824005,
 -0.025179080665111542,
 -0.008669896051287651,
 0.005810820963233709,
 0.00866303127259016,
 -0.04077528417110443,
 -0.01922067254781723,
 0.007056732662022114,
 0.0002447632432449609,
 0.012747424654662609,
 -0.0018259638454765081,
 0.013461335562169552,
 -0.004235412459820509,
 -0.033224307000637054,
 0.03750776872038841,
 -0.02973712608218193,
 -0.0010374014964327216,
 0.04884796589612961,
 -6.950332317501307e-05,
 0.0023373709991574287,
 -0.033059556037187576,
 -0.01974237710237503,
 0.00858065765351057,
 0.01201978512108326,
 0.02214496023952961,
 0.013715323060750961,
 -0.03327922150492668,
 0.043219055980443954,
 0.015733493492007256,
 0.003470017807558179,
 0.0465414859354496,
 -0.013900664635002613,
 -0.06699777394533157,
 -0.02119765616953373,
 -0.020923074334859848,
 0.04187360778450966,
 -0.01783403754234314,
 0.011669694446027279,
 -0.0031542496290057898,
 0.009225922636687756,
 -0.009678981266915798,
 -0.013179889880120754,
 0.005464162677526474,
 0.002208661288022995,
 -0.00642176391556859,
 0.014978395774960518,
 0.008367856964468956,
 0.009280839003622532,
 0.01357116736471653,
 0.009713304229080677,
 -0.03629961237311363,
 0.013626083731651306,
 0.04195598140358925,
 -0.009376942180097103,
 -0.011230364441871643,
 0.013509387150406837,
 0.03187885880470276,
 0.010104581713676453,
 0.009006258100271225,
 0.004712496884167194,
 -0.0075372494757175446,
 0.010070259682834148,
 0.02560468204319477,
 -0.0051449621096253395,
 -0.005536240059882402,
 0.004825761541724205,
 -0.005560265854001045,
 0.03418533876538277,
 -0.008024631068110466,
 0.022529374808073044,
 0.006370279937982559,
 -0.008532606065273285,
 -0.022035127505660057,
 0.004183928482234478,
 -0.003772056894376874,
 -0.012424792163074017,
 0.002601655200123787,
 -0.004884110298007727,
 -0.011944275349378586,
 0.007489197887480259,
 0.02189783751964569,
 0.022803954780101776,
 0.006473247893154621,
 -0.015307893045246601,
 -0.0009344335994683206,
 0.020140519365668297,
 -0.04816151410341263,
 0.05422975495457649,
 0.0006984655046835542,
 -0.04599232226610184,
 -0.00871108379215002,
 0.02085443027317524,
 0.016680797562003136,
 0.001892892993055284,
 0.05151140317320824,
 -0.017284875735640526,
 0.00038162473356351256,
 -0.03975933417677879,
 -0.005532807670533657,
 -0.0028865330386906862,
 0.0065933773294091225,
 -0.026908941566944122,
 -0.02852896973490715,
 -0.0026617199182510376,
 0.03198869153857231,
 -0.002697758609429002,
 1.603510281711351e-05,
 0.003984857350587845,
 0.03704098239541054,
 0.04006137326359749,
 0.0022807386703789234,
 -0.019893396645784378,
 -0.003823540871962905,
 -0.029352713376283646,
 0.0274855624884367,
 0.0014552795328199863,
 -0.0016320410650223494,
 -0.030807992443442345,
 0.002399151911959052,
 0.0009412980871275067,
 -0.02534382976591587,
 -0.012006055563688278,
 -0.015582473948597908,
 0.03489924967288971,
 0.02681283839046955,
 -0.03651927784085274,
 0.017298605293035507,
 0.017724206671118736,
 -0.037535227835178375,
 -0.0005757621256634593,
 -0.02110155299305916,
 0.008175650611519814,
 -0.01749081164598465,
 -0.00562547892332077,
 0.04533332958817482,
 1.6370286175515503e-05,
 0.015403996221721172,
 -0.03531112149357796,
 0.00611629243940115,
 0.004993942566215992,
 0.010914595797657967,
 0.013591761700809002,
 -0.02611265704035759,
 0.01442923303693533,
 -0.0025810617953538895,
 -0.03067070245742798,
 0.0147861884906888,
 0.0001893107546493411,
 0.02016797661781311,
 0.022625477984547615,
 0.011992326937615871,
 -0.025028061121702194,
 -0.017175043001770973,
 0.011230364441871643,
 0.02438279613852501,
 -0.019426608458161354,
 0.010688066482543945,
 0.04104986414313316,
 0.002864223439246416,
 -0.015472641214728355,
 0.0017358670011162758,
 0.0034151016734540462,
 -0.022295979782938957,
 0.02144477888941765,
 -0.03190631791949272,
 -0.01992085389792919,
 0.013495657593011856,
 -0.019673731178045273,
 0.0008880980312824249,
 0.013296586461365223,
 0.05656369403004646,
 -0.014813646674156189,
 -0.008978799916803837,
 -0.029544919729232788,
 -0.00965152308344841,
 -0.0028401976451277733,
 0.002526145428419113,
 -0.037095896899700165,
 -0.02170563116669655,
 0.010571369901299477,
 0.012726831249892712,
 0.008326670154929161,
 0.008374721743166447,
 -0.0012519179144874215,
 0.005223904270678759,
 -0.05876034125685692,
 -0.01716131530702114,
 -0.01136765442788601,
 0.017380978912115097,
 -0.0034477082081139088,
 0.01013203989714384,
 -0.04404279962182045,
 -0.0009018270648084581,
 -0.003445992013439536,
 0.0011506661539897323,
 0.002924287924543023,
 -0.0036347664427012205,
 0.008621844463050365,
 -0.028501510620117188,
 0.014539065770804882,
 -0.011436300352215767,
 0.000265142327407375,
 0.012184533290565014,
 0.015609932132065296,
 0.01955016888678074,
 0.020140519365668297,
 0.033993132412433624,
 0.009521097876131535,
 0.05318634584546089,
 0.0019838479347527027,
 0.01802624575793743,
 9.154489089269191e-05,
 -0.02593417838215828,
 0.013076921924948692,
 -0.026854025200009346,
 -0.0033155661076307297,
 0.002347667934373021,
 -0.021746817976236343,
 0.053735509514808655,
 -0.0439329668879509,
 0.006232989486306906,
 0.015074498951435089,
 0.007139106746762991,
 0.007015545386821032,
 0.007269532885402441,
 0.022378355264663696,
 -0.019330505281686783,
 -0.04464687779545784,
 -0.00818251445889473,
 0.0024712292943149805,
 0.017106398940086365,
 0.02162325568497181,
 -0.0008829496218822896,
 -0.07452129572629929,
 -0.03424025699496269,
 -0.012191398069262505,
 0.08006782829761505,
 -0.01765556074678898,
 -0.04530587047338486,
 0.0334165133535862,
 -0.015747223049402237,
 0.021183926612138748,
 -0.010228144004940987,
 0.005700988695025444,
 0.005364627111703157,
 -0.007550978567451239,
 0.0072489394806325436,
 -0.006843932438641787,
 -0.020030686631798744,
 -0.0012004339369013906,
 -0.010090853087604046,
 -0.068919837474823,
 -0.026222489774227142,
 -0.027183523401618004,
 0.025467390194535255,
 -0.03984170779585838,
 -0.0019100543577224016,
 0.007571571972221136,
 -0.03728810325264931,
 -0.10587844997644424,
 -0.019852207973599434,
 0.036491818726062775,
 0.007194023113697767,
 -0.02258428931236267,
 0.02224106341600418,
 0.014058548957109451,
 0.033059556037187576,
 0.02705996111035347,
 -0.02060730755329132,
 -0.01418211031705141,
 0.00041766351205296814,
 0.016159094870090485,
 0.0028487781528383493,
 -0.020579848438501358,
 -0.02325701341032982,
 0.019261859357357025,
 -0.01956389844417572,
 -0.01444296259433031,
 0.018136076629161835,
 0.014525337144732475,
 -0.0016560668591409922,
 0.025137893855571747,
 -0.009672117419540882,
 -0.019687460735440254,
 -0.013310316018760204,
 -0.044427212327718735,
 0.01529416348785162,
 0.02609892748296261,
 -0.0049081360921263695,
 0.02336684614419937,
 0.011607913300395012,
 -0.027966078370809555,
 0.01184817124158144,
 0.005052290856838226,
 0.0026325457729399204,
 -0.005072884727269411,
 -0.024959417060017586,
 0.01706521213054657,
 -0.01068120263516903,
 0.01287785079330206,
 -0.01966000162065029,
 0.010083988308906555,
 0.009219057857990265,
 0.06271430850028992,
 0.02318836934864521,
 -0.03251039609313011,
 0.02673046477138996,
 -0.025439932942390442,
 0.0249868743121624,
 0.04439975321292877,
 0.003240056335926056,
 0.02188410796225071,
 -0.020785784348845482,
 0.031494446098804474,
 0.02791116200387478,
 -0.026675548404455185,
 0.0107773058116436,
 0.018067432567477226,
 0.013886936008930206,
 -0.031604278832674026,
 -0.02222733572125435,
 0.019948313012719154,

In [18]:
len(response.data[0].embedding)

1536

In [19]:
# Function : Return embedding for a given text using OpenAI's embedding API. 
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [20]:
get_embedding("This is another sample description.")

[-0.001875470974482596,
 0.015956874936819077,
 -0.024965284392237663,
 0.00015048444038257003,
 0.006740934681147337,
 -0.014465722255408764,
 -0.006218262482434511,
 0.0013989168219268322,
 0.01571091264486313,
 0.006848543416708708,
 -0.019692445173859596,
 -0.03600289300084114,
 0.010945371352136135,
 -0.04378148540854454,
 0.03818581998348236,
 0.04015352576971054,
 -0.01872396469116211,
 0.03812432661652565,
 -0.028962191194295883,
 0.05678680166602135,
 0.03750941902399063,
 -0.0029842278454452753,
 0.019738562405109406,
 0.044580865651369095,
 0.012321229092776775,
 -0.04501130431890488,
 -0.025918394327163696,
 -0.007932319305837154,
 0.06776291877031326,
 -0.03240567818284035,
 0.028085945174098015,
 -0.04867000877857208,
 0.005937710404396057,
 -0.02899293601512909,
 0.010568739846348763,
 0.023673977702856064,
 0.04983833432197571,
 -0.01068403571844101,
 -0.005603353958576918,
 -0.02890069968998432,
 -0.001173130120150745,
 -0.06253619492053986,
 0.013051432557404041,
 0.020322725176811218,
 0.025226620957255363,
 0.03926190733909607,
 -0.024350376799702644,
 -0.025641685351729393,
 0.028070572763681412,
 0.046763792634010315,
 -0.03403518721461296,
 -0.01877008192241192,
 0.009930772706866264,
 -0.021567916497588158,
 -0.005968455690890551,
 -0.011913851834833622,
 -0.006033789832144976,
 0.04596441239118576,
 0.007866986095905304,
 -0.020722417160868645,
 0.012959197163581848,
 -0.009400413371622562,
 -0.014135208912193775,
 0.03923116251826286,
 -0.03532649204134941,
 0.020860770717263222,
 -0.011029921472072601,
 0.012820842675864697,
 -0.029484862461686134,
 0.007144468370825052,
 0.046917520463466644,
 0.00951570924371481,
 -0.040737688541412354,
 0.020138254389166832,
 0.014189014211297035,
 0.01022285409271717,
 -0.05694052577018738,
 -0.043597012758255005,
 -0.00606837822124362,
 0.006441166624426842,
 0.012859273701906204,
 0.02252102456986904,
 -0.007647924590855837,
 -0.0487622432410717,
 -0.005576451309025288,
 -0.012421151623129845,
 -0.07840083539485931,
 -0.007490354124456644,
 0.007790122181177139,
 0.017002219334244728,
 -0.002161787822842598,
 -0.02536497637629509,
 0.0010799330193549395,
 -0.012697860598564148,
 0.0394156351685524,
 -0.0017938034143298864,
 -0.00837812852114439,
 -0.01887769065797329,
 0.008747073821723461,
 0.016018366441130638,
 0.014158268459141254,
 -0.017494147643446922,
 0.018431883305311203,
 0.027424918487668037,
 0.055987417697906494,
 -0.04116812348365784,
 -0.006952309049665928,
 0.0017534500220790505,
 -0.04258241504430771,
 -0.01717131957411766,
 -0.0502995140850544,
 0.001849529449827969,
 0.023166678845882416,
 0.04602590203285217,
 0.0032244264148175716,
 0.017909210175275803,
 0.06973062455654144,
 0.010069127194583416,
 -0.028301164507865906,
 -0.02853175438940525,
 -0.022182824090123177,
 -0.050545480102300644,
 0.0373556911945343,
 -0.07120640575885773,
 -0.003053405089303851,
 -0.056202638894319534,
 0.02433500438928604,
 0.002586458809673786,
 -0.05260542407631874,
 0.026179729029536247,
 0.008070673793554306,
 -0.0037663145922124386,
 -0.03895445540547371,
 -0.012528760358691216,
 -0.036125876009464264,
 0.01966170035302639,
 -0.030822288244962692,
 0.001843764679506421,
 -0.030776171013712883,
 -0.016787001863121986,
 0.005038406699895859,
 -0.015065258368849754,
 0.0404609814286232,
 0.02479618601500988,
 0.017601756379008293,
 -0.03112974390387535,
 -0.015787776559591293,
 0.05789363756775856,
 -0.003973846323788166,
 -0.0018745101988315582,
 -0.02536497637629509,
 0.01566479355096817,
 -0.09660212695598602,
 -0.003756706602871418,
 -0.028762346133589745,
 -0.036494821310043335,
 0.038831472396850586,
 0.0019734720699489117,
 -0.0679473876953125,
 0.030069025233387947,
 -0.008639464154839516,
 -0.02459634095430374,
 0.014619450084865093,
 0.00988465454429388,
 -0.022843850776553154,
 -0.02634882926940918,
 -0.00422749575227499,
 0.014673254452645779,
 -0.06665608286857605,
 -0.03821656480431557,
 -0.006275909952819347,
 0.0036798431538045406,
 0.007993810810148716,
 0.015072944574058056,
 -0.003128346987068653,
 0.02573392167687416,
 0.017401911318302155,
 -0.0015247808769345284,
 0.017079083248972893,
 0.02702522836625576,
 -0.004504204727709293,
 0.0451342836022377,
 0.02375084161758423,
 0.023535622283816338,
 -0.024319631978869438,
 -0.05149858817458153,
 0.02064555324614048,
 0.03212897107005119,
 0.04430415853857994,
 -0.012098324485123158,
 0.01706371083855629,
 0.006825484335422516,
 -0.0017765091033652425,
 0.006867759395390749,
 -0.01913902722299099,
 -0.032651640474796295,
 0.057401709258556366,
 -0.0028919915203005075,
 0.010430385358631611,
 -0.02879309095442295,
 0.014427291229367256,
 -0.023627858608961105,
 0.011575652286410332,
 0.006375832483172417,
 -0.03609512746334076,
 0.0013576026540249586,
 -0.0089469188824296,
 -0.04052247107028961,
 0.005468842573463917,
 -0.025903020054101944,
 0.03849327191710472,
 0.0032628581393510103,
 0.027471037581562996,
 0.0017822738736867905,
 -0.06115265190601349,
 0.014035286381840706,
 -0.020092135295271873,
 0.02682538330554962,
 0.02604137547314167,
 -0.019784681499004364,
 0.00469252048060298,
 0.03403518721461296,
 0.051283370703458786,
 0.06370452046394348,
 -0.049100443720817566,
 0.03335878625512123,
 -0.02184462547302246,
 -0.024181276559829712,
 -0.023320404812693596,
 -0.06518030166625977,
 0.03646407276391983,
 0.017663246020674706,
 -0.014219759032130241,
 -0.05451164022088051,
 -0.02079928107559681,
 0.01961558125913143,
 -0.03096064366400242,
 -0.00835506897419691,
 -0.006337400991469622,
 -0.004803972784429789,
 -0.04070694372057915,
 0.008255146443843842,
 0.021245088428258896,
 -0.007970751263201237,
 0.026271965354681015,
 0.0030956799164414406,
 0.0008137929835356772,
 -0.05949239805340767,
 0.03154480457305908,
 0.016095230355858803,
 0.027624765411019325,
 0.047378700226545334,
 -0.027517154812812805,
 -0.04574919119477272,
 -0.03243642300367355,
 0.009615631774067879,
 -0.0004388428933452815,
 0.010138303972780704,
 -0.0013556811027228832,
 -0.0384010374546051,
 0.0021291207522153854,
 -0.0415063239634037,
 -0.03283611312508583,
 0.02883920818567276,
 -0.04282837733626366,
 0.02905442751944065,
 0.0881778821349144,
 0.015549498610198498,
 -0.0023962215054780245,
 -0.013243592344224453,
 -0.02691761963069439,
 0.009869281202554703,
 0.0363103486597538,
 0.03692525625228882,
 -0.03916967287659645,
 0.005726335570216179,
 -0.01122976653277874,
 -0.010707094334065914,
 0.016049111261963844,
 0.02084539830684662,
 -0.014873099513351917,
 -0.06302811950445175,
 0.015757029876112938,
 0.017032966017723083,
 -0.01887769065797329,
 -0.002859324449673295,
 0.03342027589678764,
 -0.00688697537407279,
 0.023612486198544502,
 0.03938489034771919,
 0.015757029876112938,
 -0.02458096668124199,
 -0.00481165898963809,
 -0.045718446373939514,
 -0.042982105165719986,
 -0.009969203732907772,
 0.02132195234298706,
 0.02986918017268181,
 0.02717895619571209,
 -0.001694841543212533,
 0.022182824090123177,
 0.0024500261060893536,
 0.022966831922531128,
 0.025380348786711693,
 0.026932992041110992,
 0.02059943415224552,
 0.01721743866801262,
 -0.035265002399683,
 0.020507197827100754,
 -0.003332035383209586,
 0.040276508778333664,
 -0.020107507705688477,
 -0.016418056562542915,
 0.010499563068151474,
 -0.014135208912193775,
 -0.06739397346973419,
 0.06438092142343521,
 -0.009200568310916424,
 0.006956152617931366,
 -0.0006816837121732533,
 0.027040600776672363,
 -0.022013723850250244,
 0.0612141415476799,
 -0.014288936741650105,
 -0.015288162976503372,
 0.01850874535739422,
 -0.010438071563839912,
 -0.01706371083855629,
 0.06115265190601349,
 -0.012874647043645382,
 0.015288162976503372,
 -0.02127583511173725,
 0.008324324153363705,
 -0.029946044087409973,
 0.01341269165277481,
 -0.02873159945011139,
 0.0011760125635191798,
 0.024411868304014206,
 0.018893063068389893,
 0.03465009480714798,
 -0.07710952311754227,
 -0.04353552311658859,
 0.003985375631600618,
 0.006798582151532173,
 -0.010783958248794079,
 0.02282847836613655,
 -0.011475729756057262,
 0.020768534392118454,
 0.01893918216228485,
 -0.007432706654071808,
 -0.01169863436371088,
 -0.023612486198544502,
 0.022597886621952057,
 0.03548021987080574,
 0.008193655870854855,
 -0.044273413717746735,
 0.01132968906313181,
 -0.011152902618050575,
 -0.028654735535383224,
 -0.009715554304420948,
 -0.016479548066854477,
 0.04218272492289543,
 0.02759401872754097,
 0.0007244391017593443,
 0.0007138703367672861,
 0.045103538781404495,
 -0.02189074270427227,
 -0.04783987998962402,
 0.006733248010277748,
 -0.01361253671348095,
 -0.01950797252357006,
 0.033481769263744354,
 -0.035357240587472916,
 -0.0011779341148212552,
 -0.04433490335941315,
 -0.02225968800485134,
 -0.017924582585692406,
 -0.0006932132528163493,
 -0.003733647521585226,
 0.013159042224287987,
 -0.01568785309791565,
 0.0384010374546051,
 -0.026640910655260086,
 0.000742694188375026,
 0.0523902028799057,
 -0.015526439994573593,
 0.00503072002902627,
 0.025549449026584625,
 -0.041998252272605896,
 0.0018110977252945304,
 0.007205958943814039,
 -0.02971545420587063,
 0.042305704206228256,
 0.0178938377648592,
 -0.03987681493163109,
 0.019154399633407593,
 0.03584916517138481,
 0.04067619889974594,
 -0.023212796077132225,
 0.0041314163245260715,
 0.0011567965848371387,
 -0.03157555311918259,
 -0.02516513131558895,
 0.05512654781341553,
 -0.05518803745508194,
 -0.0005154662649147213,
 -0.015741657465696335,
 0.012013775296509266,
 0.027532529085874557,
 -0.0378783643245697,
 0.01774010993540287,
 -0.018385764211416245,
 0.024565594270825386,
 -0.013689400628209114,
 0.0036952157970517874,
 0.005591824185103178,
 0.00517676118761301,
 0.06023028865456581,
 0.03517276793718338,
 0.024857675656676292,
 0.018447255715727806,
 -0.005441940389573574,
 0.0017649795627221465,
 -0.009131391532719135,
 0.02770162746310234,
 0.020937634631991386,
 0.0027517154812812805,
 -0.04239794239401817,
 -0.01638731174170971,
 -0.05331256613135338,
 0.028916072100400925,
 -0.0015843502478674054,
 -0.046394847333431244,
 0.0017534500220790505,
 0.002348181791603565,
 -0.030330361798405647,
 -0.002853559795767069,
 -0.015595616772770882,
 0.010268972255289555,
 -0.020922262221574783,
 0.0032628581393510103,
 -0.03606438264250755,
 -0.005611040163785219,
 -0.0026594793889671564,
 -0.03938489034771919,
 0.015134435147047043,
 0.005657158326357603,
 -0.00492695439606905,
 0.0029073641635477543,
 0.009784732013940811,
 -0.025872275233268738,
 0.0012365425936877728,
 -0.03655631095170975,
 0.05767841637134552,
 0.014388859272003174,
 -0.011660202406346798,
 -0.00972324050962925,
 0.016771629452705383,
 0.06321259588003159,
 -0.039446379989385605,
 0.04036874324083328,
 0.02121434360742569,
 0.0027805394493043423,
 0.03360474854707718,
 -0.013166728429496288,
 -0.024457985535264015,
 0.006940779741853476,
 0.006114496383816004,
 0.012651742435991764,
 -0.018016818910837173,
 0.027947591617703438,
 0.0008844113908708096,
 0.018893063068389893,
 0.03157555311918259,
 -0.0024442612193524837,
 -0.00954645499587059,
 0.030253497883677483,
 -0.039354145526885986,
 0.022490277886390686,
 0.007916946895420551,
 0.011283570900559425,
 0.041783031076192856,
 -0.06843931972980499,
 0.010445757769048214,
 0.02219819650053978,
 0.059307925403118134,
 0.014542586170136929,
 0.01586463861167431,
 0.017002219334244728,
 -0.024703949689865112,
 -0.005111427046358585,
 0.021398816257715225,
 0.022075215354561806,
 -0.01872396469116211,
 -0.012482642196118832,
 0.0021579444874078035,
 0.023074442520737648,
 -0.08319712430238724,
 0.03329729661345482,
 0.004215966444462538,
 -0.018800826743245125,
 0.019800053909420967,
 0.027363428846001625,
 0.07046851515769958,
 0.03122198022902012,
 -0.01883157342672348,
 -0.040491726249456406,
 0.03738643601536751,
 -0.015680165961384773,
 0.025134384632110596,
 -0.03575693070888519,
 0.02225968800485134,
 0.019569464027881622,
 -0.026687029749155045,
 -0.0110222352668643,
 -0.009215941652655602,
 -0.0075941202230751514,
 0.011291257105767727,
 -0.01205989345908165,
 0.000722517492249608,
 -0.0001028050173772499,
 0.034834567457437515,
 -0.016894610598683357,
 -0.012259738519787788,
 -0.012021461501717567,
 -0.01850874535739422,
 0.0025441839825361967,
 -0.04993056878447533,
 -0.012259738519787788,
 0.000874803401529789,
 0.006936936639249325,
 0.002597988350316882,
 0.036341093480587006,
 0.05149858817458153,
 -0.02681001089513302,
 -0.050238024443387985,
 0.02754790149629116,
 0.013235905207693577,
 0.01564173586666584,
 -0.02167552523314953,
 0.010768584907054901,
 0.01159102562814951,
 0.0002620567101985216,
 -0.053404804319143295,
 0.008239774033427238,
 0.023212796077132225,
 0.016172094270586967,
 0.035295747220516205,
 -0.0008714406285434961,
 0.01236734725534916,
 0.002486536279320717,
 -0.02261326089501381,
 0.02905442751944065,
 -0.0068754456005990505,
 -0.021552542224526405,
 0.0007412529666908085,
 -0.008969977498054504,
 -0.008193655870854855,
 -0.017340419813990593,
 -0.03790910914540291,
 0.006298969034105539,
 0.022444160655140877,
 0.010845448821783066,
 0.004711736459285021,
 -0.006902347784489393,
 0.04285912215709686,
 0.022182824090123177,
 0.03584916517138481,
 0.03437338396906853,
 -0.009953831322491169,
 -0.03148331493139267,
 -0.025534074753522873,
 -0.03661780059337616,
 -0.0007028211839497089,
 -0.03323580324649811,
 0.0009761672699823976,
 0.037171218544244766,
 -0.022428788244724274,
 0.010046067647635937,
 -0.0004097788769286126,
 0.005468842573463917,
 -0.047747645527124405,
 -0.0014469565358012915,
 0.062167249619960785,
 -0.02391993999481201,
 0.0007191547192633152,
 0.056663818657398224,
 0.007993810810148716,
 -0.0399383082985878,
 0.0215217974036932,
 0.007229018025100231,
 -0.01690998300909996,
 -0.02033809944987297,
 0.014411917887628078,
 0.02261326089501381,
 0.000533240963704884,
 -0.022813105955719948,
 0.013919991441071033,
 -0.018247410655021667,
 -0.013927677646279335,
 0.022843850776553154,
 0.009738613851368427,
 -0.001115482416935265,
 -0.015757029876112938,
 -0.011183648370206356,
 0.02573392167687416,
 -0.0199691541492939,
 0.004023807588964701,
 0.02058406174182892,
 0.0023212796077132225,
 0.0012144442880526185,
 0.027717001736164093,
 -0.0020176684483885765,
 -0.021383443847298622,
 0.010653289966285229,
 0.0033704673405736685,
 -0.030099771916866302,
 0.006798582151532173,
 0.05337405949831009,
 0.008754760026931763,
 0.023120559751987457,
 0.0019830798264592886,
 0.007770906202495098,
 -0.02459634095430374,
 -0.021183598786592484,
 0.05903121829032898,
 0.007117565721273422,
 -0.0332050584256649,
 -0.04627186432480812,
 0.0014728980604559183,
 0.008162910118699074,
 0.0015574479475617409,
 0.07409647852182388,
 -0.016264330595731735,
 -0.009638690389692783,
 -0.03286685794591904,
 -0.005568765103816986,
 0.010199794545769691,
 0.002882383530959487,
 -0.019431108608841896,
 -0.022582514211535454,
 0.023120559751987457,
 0.006383518688380718,
 -0.026794638484716415,
 -0.003314741188660264,
 -0.026471810415387154,
 0.060568489134311676,
 0.03148331493139267,
 -0.006348930299282074,
 -0.02857787348330021,
 -0.024611713364720345,
 -0.03932340070605278,
 0.023059068247675896,
 0.03351251408457756,
 -0.018247410655021667,
 -0.03701749071478844,
 -0.023796958848834038,
 0.0030015220399945974,
 -0.03624885529279709,
 -0.028147436678409576,
 -0.03191374987363815,
 0.04227495938539505,
 -0.005653315223753452,
 -0.03720196336507797,
 0.010899253189563751,
 0.01867784559726715,
 -0.016418056562542915,
 -0.015096004121005535,
 -0.009554141201078892,
 0.0415063239634037,
 0.003750941948965192,
 -0.004807815887033939,
 0.05998432636260986,
 0.017770856618881226,
 0.007094507105648518,
 0.0002656596770975739,
 -0.003927728161215782,
 -0.032805368304252625,
 -0.010499563068151474,
 -0.010645603761076927,
 0.0009915399132296443,
 0.005053779110312462,
 0.025026775896549225,
 -0.020414961501955986,
 0.04061470553278923,
 0.002371240872889757,
 0.03606438264250755,
 -0.005795512814074755,
 0.00356070464476943,
 -0.0037816872354596853,
 -0.004446557257324457,
 0.04783987998962402,
 0.022428788244724274,
 -0.030330361798405647,
 0.005157545208930969,
 -0.04445788636803627,
 -0.02084539830684662,
 0.01548800803720951,
 0.0025653215125203133,
 -0.02608749270439148,
 -0.03511127457022667,
 0.018647100776433945,
 -0.03086840733885765,
 -0.015049885958433151,
 -0.022382669150829315,
 0.00377976568415761,
 0.04196750372648239,
 0.023535622283816338,
 0.06259768456220627,
 -0.02433500438928604,
 0.008893114514648914,
 -0.04104514420032501,
 -0.03833954408764839,
 0.01451952662318945,
 0.002509595360606909,
 -0.03938489034771919,
 -0.03440413251519203,
 -0.021152852103114128,
 0.010145990177989006,
 -0.0058608464896678925,
 0.036279600113630295,
 0.02468857727944851,
 0.027102092280983925,
 -0.06456539034843445,
 -0.004938483703881502,
 0.009823163039982319,
 0.025641685351729393,
 -0.002136806957423687,
 0.017970701679587364,
 -0.07354305684566498,
 0.006825484335422516,
 0.003155249170958996,
 -0.010799330659210682,
 -0.0031245038844645023,
 0.01262868382036686,
 0.0003948865632992238,
 -0.006933093536645174,
 0.01920051872730255,
 -0.01577240228652954,
 -0.014634822495281696,
 0.03222120553255081,
 -0.005814728327095509,
 -0.026394948363304138,
 0.002546105533838272,
 0.02733268216252327,
 -0.006049162242561579,
 0.040337998420000076,
 0.005391979124397039,
 -0.0057993559166789055,
 -0.0032590150367468596,
 -0.03157555311918259,
 0.014965335838496685,
 -0.03707898408174515,
 0.0006619874620810151,
 0.03169853240251541,
 -0.038308799266815186,
 0.06099892407655716,
 -0.022029096260666847,
 0.018078310415148735,
 -0.0160798579454422,
 -0.0018649022094905376,
 0.023581741377711296,
 0.006033789832144976,
 0.03338953107595444,
 -0.017986074090003967,
 -0.00780549505725503,
 -0.008462678641080856,
 -0.02049182541668415,
 0.005488058552145958,
 0.026072120293974876,
 0.024857675656676292,
 -0.04553397372364998,
 -0.011683261953294277,
 -0.011652516201138496,
 0.06942316889762878,
 0.014511840417981148,
 0.0043312618508934975,
 0.026287337765097618,
 0.0008527051541022956,
 0.01577240228652954,
 0.009446531534194946,
 0.0003766314475797117,
 -0.00016921994392760098,
 0.008001497015357018,
 0.023673977702856064,
 -0.003443487687036395,
 -0.012290483340620995,
 -0.011952283792197704,
 -0.03406593203544617,
 -0.04076843336224556,
 0.008831623010337353,
 -0.0032667014747858047,
 0.03855476155877113,
 -0.013520300388336182,
 -0.006579521112143993,
 0.030053652822971344,
 -0.016464175656437874,
 -0.13368110358715057,
 0.0036683136131614447,
 0.007271293085068464,
 0.010084499605000019,
 -0.0399383082985878,
 0.030730051919817924,
 0.02962321788072586,
 0.05116038769483566,
 0.031252723187208176,
 -0.044642359018325806,
 -0.01955408975481987,
 -0.017048338428139687,
 -0.0028228142764419317,
 0.0001098308275686577,
 -0.01981542631983757,
 -0.006994584109634161,
 -0.0063796755857765675,
 -0.006867759395390749,
 -0.014158268459141254,
 -0.006971525028347969,
 0.010445757769048214,
 -0.021091362461447716,
 -0.021537169814109802,
 -0.03314356878399849,
 -0.036802273243665695,
 -0.0178938377648592,
 -0.08159835636615753,
 -0.006894661579281092,
 0.03972309082746506,
 0.002421202138066292,
 0.03584916517138481,
 0.0029573256615549326,
 -0.01270554680377245,
 -0.0027690099086612463,
 -0.00918519590049982,
 -0.005641785450279713,
 -0.013266650959849358,
 -0.013958423398435116,
 0.020768534392118454,
 0.0024846147280186415,
 0.004377380013465881,
 -0.046856027096509933,
 0.01200608815997839,
 0.017909210175275803,
 0.05309734866023064,
 -0.005238251760601997,
 -0.054480891674757004,
 0.019308127462863922,
 -0.016418056562542915,
 0.024565594270825386,
 0.04135259613394737,
 0.008808564394712448,
 0.04122961685061455,
 0.004200593568384647,
 0.013220532797276974,
 0.04491906613111496,
 -0.016510292887687683,
 -0.003739412408322096,
 -0.0031072094570845366,
 0.03947712481021881,
 0.004442714154720306,
 -0.025856902822852135,
 0.015103690326213837,
 0.002033041324466467,

### Create a Qdrant collection

In [21]:
qdrant_client = QdrantClient(url="http://localhost:6333") # Connect to the Qdrant vector database running in the Docker container

In [22]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-00", # Name of the collection in Qdrant where our item embeddings will be stored
    vectors_config= VectorParams(size= 1536, distance=Distance.COSINE) 
)

True

#### Embed data

In [ ]:
# Test 1

# PointStruct is a data structure used to represent a point in the vector space, which includes;
# 1. ID 
# 2. the vector itself (the embedding), 
# 3. additional payload (metadata) associated with that point

pointstruct = PointStruct(
    id=0,
    vector = get_embedding("Test text"),
    payload = {
        "test": "Test text",
        "model": "text-embedding-3-small"
    }
)

In [25]:
pointstruct

PointStruct(id=0, vector=[-0.020057253539562225, 0.006970119196921587, 0.037700485438108444, -0.040323127061128616, -0.01916317082941532, -0.0343029722571373, 0.0005480913096107543, -0.02425944246351719, 0.03871377930045128, 0.0015953787369653583, 0.030667034909129143, 0.012792832218110561, -0.010863103903830051, 0.011287793517112732, 0.02639034017920494, 0.04303517937660217, -0.046820126473903656, -0.00690678833052516, -0.02174110896885395, 0.05108192190527916, 0.0070856050588190556, 0.013113211840391159, 0.01130269467830658, -0.032544609159231186, -0.00393396383151412, -0.039041608572006226, -0.036955416202545166, 0.004965884145349264, 0.05841339752078056, -0.07462609559297562, 0.031382299959659576, -0.044018667191267014, -0.00025891143013723195, -0.010974864475429058, 0.006005255039781332, 0.03814752772450447, 0.03030940145254135, 0.037640880793333054, 0.010274499654769897, -0.029355714097619057, -0.014916278421878815, -0.010386260226368904, 0.021279167383909225, 0.018149876967072487, 0.02658405713737011, 0.008940826170146465, -0.011861496604979038, 0.008814164437353611, 0.019952943548560143, 0.03790910542011261, -0.03635936230421066, 0.01072154100984335, 0.0180604699999094, 0.017240893095731735, 0.02229246124625206, -0.0006305145216174424, -0.046998944133520126, 0.04071056470274925, -0.003473883494734764, -0.0003019857394974679, 0.024423357099294662, 0.01543782651424408, 0.006545430049300194, 0.006917964201420546, -0.0054390025325119495, -0.003609858686104417, 0.011466610245406628, 0.011593271978199482, -0.003455256810411811, -0.0030976238194853067, 0.0290874894708395, 0.015288813039660454, -0.05382377654314041, 0.001580477342940867, -0.04842947795987129, -0.007882828824222088, -0.004086702596396208, 0.045657820999622345, -0.025675073266029358, -0.0035912320017814636, 0.03278303146362305, 0.0303243026137352, -0.012330889701843262, -0.02291831746697426, -0.04640289023518562, 0.029191797599196434, -0.12660209834575653, -0.0037607350386679173, -0.009738050401210785, -0.06282420456409454, -0.005912121385335922, -0.03239559382200241, -0.0029448845889419317, -0.009469824843108654, 0.039667464792728424, -0.03376651927828789, -0.011652876622974873, -0.002326477551832795, -0.016212698072195053, 0.004280420485883951, 0.02738873101770878, 0.0030119409784674644, -0.011585820466279984, 0.02020626701414585, 0.007778518833220005, 0.03939924016594887, 0.01347084529697895, -0.008136152289807796, -0.03260421380400658, 0.017121681943535805, -0.04079997166991234, -0.02008705586194992, 0.0001558823714731261, -0.02217325009405613, 0.009633740410208702, -0.018820440396666527, 0.075937420129776, -0.08040783554315567, 0.0001582107215654105, -0.054598648101091385, 0.021592095494270325, 0.008858868852257729, 0.022992825135588646, -0.028804361820220947, -0.0023395163007080555, -0.06240696832537651, -0.004224540665745735, -0.07528176158666611, -0.022858712822198868, 0.013664563186466694, 0.014774715527892113, -0.01292694453150034, 0.022277558222413063, 0.038982003927230835, -0.05617819353938103, 0.04282655939459801, -0.037581272423267365, 0.018045568838715553, -0.04974079877138138, 0.05936708673834801, -0.03290224075317383, 0.024095527827739716, 0.0009448404307477176, 0.001196766854263842, -0.01142190583050251, -0.050873301923274994, -0.03287243843078613, 0.004366103559732437, 0.032127369195222855, 0.02957923337817192, -0.024453159421682358, 0.021279167383909225, -0.03928003087639809, 0.002196090528741479, 0.028804361820220947, -0.01181679219007492, -0.0023581429850310087, 0.005275087431073189, -0.01460334938019514, -0.05364495888352394, 0.019744325429201126, -0.02020626701414585, 0.0416344478726387, 0.016451120376586914, -0.02652445249259472, 0.0074655902571976185, 0.0266436617821455, -0.02761225216090679, -0.04544920101761818, 0.021711306646466255, 0.018269088119268417, -0.016808753833174706, -0.02965374104678631, -0.0018421828281134367, -0.04056154936552048, 0.0026543077547103167, 0.009015332907438278, 0.015616643242537975, -0.013381436467170715, 0.027299324050545692, 0.015765657648444176, 0.045896243304014206, 0.01411905512213707, 0.019997648894786835, -0.0055395872332155704, -0.013105761259794235, 0.04330340400338173, 0.024944905191659927, -0.01145915873348713, 0.005684875417500734, -0.0147002087906003, -0.01691306382417679, 0.03835614398121834, 0.01344104204326868, -0.007391083054244518, -0.057727936655282974, 0.05769813433289528, -0.016212698072195053, -0.04172385483980179, 0.03740245848894119, 0.021055646240711212, 0.024527667090296745, -0.00802439171820879, 0.011123877950012684, -0.015631545335054398, -0.0030380182433873415, -0.05936708673834801, 0.02652445249259472, -0.015780558809638023, -0.04035292938351631, 0.08213639259338379, -0.015720952302217484, -0.009037685580551624, -0.025198228657245636, -0.018045568838715553, -0.024602174758911133, -0.016942866146564484, 0.0003527435474097729, 0.046879734843969345, 0.016153093427419662, 0.0029635115060955286, 0.027820872142910957, 0.0722418799996376, 0.005424101371318102, 0.0035092744510620832, 0.0465519018471241, 0.028774559497833252, 0.006310733500868082, -0.013597507029771805, -0.055284108966588974, -0.004910003859549761, 0.004906278569251299, 0.01374652050435543, -0.01750911772251129, 0.028163602575659752, 0.0009276107302866876, -0.020429788157343864, 0.01558684092015028, -0.02804439142346382, 0.015184503048658371, -0.07617583870887756, 0.002283636014908552, 0.011123877950012684, 0.02695659175515175, 0.01971452310681343, -0.012636368162930012, 0.0017658132128417492, -0.04294576868414879, 0.039965495467185974, -0.01022979523986578, 0.02853613719344139, -0.00613936735317111, -0.016018981114029884, -0.033468492329120636, 0.01022979523986578, -0.0028647896833717823, 0.0021402102429419756, 0.008106349036097527, 0.038922399282455444, -0.006236226297914982, -0.047744013369083405, -0.024646878242492676, -0.05352574586868286, -0.03621034696698189, -0.026137016713619232, 0.011906200088560581, 0.055760953575372696, -0.03179953992366791, 0.006731697358191013, -0.07194384932518005, -0.0020023726392537355, 0.010691738687455654, 0.06568527221679688, -0.0006300488603301346, -0.03933963552117348, 0.04613466560840607, -0.02798478677868843, -0.022754402831196785, 0.005249009933322668, 0.03951845318078995, -0.04851888492703438, -0.002771656261757016, -0.03853496164083481, 0.00019069106201641262, -0.011272892355918884, -0.005826438311487436, -0.002505294047296047, -0.017658133059740067, 0.002015411388128996, 0.0489957295358181, -0.004433159716427326, -0.03147171065211296, 0.05054547265172005, -0.004343751352280378, -0.00017427626880817115, 0.029847458004951477, 0.001356956665404141, -0.009723148308694363, -0.0003485525376163423, -0.009141994640231133, 0.04196227714419365, 0.03546527773141861, 0.02431904710829258, 0.010483118705451488, -0.004179836250841618, 0.012293635867536068, 0.014007294550538063, -0.015571939758956432, 0.008091447874903679, -0.01764323003590107, 0.016004079952836037, 0.05075409263372421, 0.010848202742636204, -0.03269362077116966, -0.027791067957878113, -0.05641661584377289, 0.004679032601416111, 0.022501079365611076, 0.026137016713619232, -0.04917454347014427, 0.03993568941950798, -0.0336771123111248, 0.04494255408644676, 0.024900201708078384, -0.011742285452783108, 0.020101958885788918, 0.018582018092274666, -0.020608603954315186, 0.0343029722571373, 0.017375005409121513, -0.05373436585068703, -0.010185091756284237, 0.009484726935625076, -0.03510764613747597, 0.028506334871053696, 0.011161131784319878, 0.013411239720880985, 0.07671228796243668, 0.024706482887268066, 0.05805576592683792, -0.026315832510590553, 0.02485549822449684, -0.013642210513353348, -0.012561861425638199, 0.03933963552117348, 0.0015367044834420085, -0.003911611624062061, 0.03603152930736542, 0.05951610207557678, 0.02247127704322338, -0.013403789140284061, 0.004343751352280378, 0.035524882376194, -0.015571939758956432, 0.06359907984733582, -0.05310850962996483, -0.046939339488744736, 0.023112036287784576, 0.027046000584959984, -0.014059449546039104, 0.029907064512372017, 0.017926357686519623, 0.02536214329302311, 0.030398810282349586, 0.027418535202741623, 0.028223209083080292, -0.03475001081824303, 0.009492177516222, -0.005927023012191057, 0.004582173656672239, -0.013090860098600388, 0.03916081786155701, 0.02412533015012741, 0.009492177516222, -0.05072428658604622, 0.008769460953772068, -0.021636798977851868, 0.02774636447429657, 0.03343869000673294, 0.03117368184030056, -0.029296107590198517, 0.02203913778066635, 0.007134034298360348, -0.033349283039569855, 0.035495080053806305, 0.002961648628115654, 0.011772087775170803, 0.03618054464459419, -0.026122113689780235, 0.010006275027990341, 0.05567154660820961, 0.016555430367588997, -0.01831379346549511, 0.01677895151078701, 0.013798675499856472, 0.029549431055784225, -0.008560840971767902, 0.057727936655282974, 0.02272460050880909, 0.00152366585098207, 0.05582055822014809, -0.03913101553916931, -0.05167797580361366, 0.004064350854605436, -0.029445121064782143, 0.007432061713188887, -0.017717737704515457, 0.02457237057387829, 0.010870554484426975, -0.04720756411552429, 0.03773028776049614, 0.0027902829460799694, 0.03123328648507595, -0.00479079270735383, -0.015974275767803192, 0.01458099763840437, 0.05409200116991997, 0.055880166590213776, 0.017181288450956345, 0.020161563530564308, -0.034451983869075775, -0.008739657700061798, -0.01295674778521061, -0.020593702793121338, -0.006269754376262426, 0.03641896694898605, 0.04512137174606323, -0.010147837921977043, 0.0033695739693939686, -0.016138192266225815, -0.022709699347615242, 0.007778518833220005, -0.02719501405954361, 0.03361750766634941, -0.03841575235128403, -0.005360770504921675, -0.012241481803357601, 0.04330340400338173, -0.014536293223500252, -0.01393278781324625, -0.01046821754425764, 0.005811537150293589, -0.007733814883977175, -0.0012647544499486685, -0.03576330468058586, 0.021830517798662186, 0.006660915445536375, 0.0023637309204787016, 0.002661758568137884, -0.03284263610839844, -0.02573467791080475, -0.04491275176405907, -0.0049919611774384975, -0.05579075589776039, 0.009134544059634209, -0.0275526475161314, 0.018269088119268417, 0.02203913778066635, 0.03117368184030056, 0.015318616293370724, -0.001533910515718162, -0.015706051141023636, -0.012435199692845345, 0.030428612604737282, -0.006228775717318058, -0.02308223396539688, 0.054419830441474915, 0.04023372009396553, 0.05841339752078056, -0.026613859459757805, -0.025436650961637497, -0.0028610643930733204, -0.00023178626724984497, -0.014662954956293106, 0.01874593272805214, -0.024035921320319176, 0.016212698072195053, -0.010408611968159676, -0.03576330468058586, -0.037760090082883835, 0.013783774338662624, -0.01984863542020321, -0.04267754405736923, 0.004217089619487524, -0.020176464691758156, 0.157954603433609, -0.033587705343961716, 0.006329359952360392, -0.001464991713874042, -0.033587705343961716, -0.04369083791971207, 0.01665974035859108, 0.0066273873671889305, -0.01868632808327675, 0.008367123082280159, -0.005986628122627735, 0.05918826907873154, -0.008285165764391422, 0.01555703766644001, -0.054419830441474915, -0.010706639848649502, 0.006500725634396076, -0.030667034909129143, 0.023439867421984673, 0.05474765971302986, 0.005826438311487436, -0.006869534961879253, -0.000662179954815656, 0.02707580290734768, -0.00230412557721138, -0.0032112468034029007, 0.010334105230867863, -0.002199815819039941, 0.0006705619744025171, -0.016689542680978775, 0.012502255849540234, -0.015273911878466606, 0.017956160008907318, -0.015109996311366558, -0.007778518833220005, 0.0001378377346554771, 0.022426573559641838, -0.013597507029771805, -0.012286185286939144, -0.02075761929154396, -0.04607505723834038, -0.03409435227513313, -0.05009843036532402, 0.006280930712819099, -0.006172895431518555, -0.004787067417055368, 0.006646014284342527, 0.06467197835445404, -0.016495823860168457, -0.024021020159125328, -0.043571628630161285, -0.00964864157140255, 0.020042352378368378, 0.02309713512659073, -0.013947688974440098, 0.030905457213521004, 0.018269088119268417, 0.02504921518266201, -0.00848633423447609, -0.013098310679197311, 0.03153131529688835, -0.008054194040596485, 0.008903573267161846, -0.014662954956293106, -0.0038259285502135754, 0.01691306382417679, -0.042290110141038895, 0.016868358477950096, 0.010594879277050495, 0.031382299959659576, 0.011436806991696358, 0.007040900643914938, 0.004101604223251343, -0.0029039059299975634, -0.0039600408636033535, 0.0030957611743360758, -0.011690130457282066, 0.015072743408381939, -0.03197835758328438, -0.024766089394688606, 0.021145055070519447, -0.027105605229735374, -0.01581036113202572, 0.049263954162597656, 0.013597507029771805, -0.007208541501313448, 0.02928120642900467, -0.035435475409030914, -0.015132348984479904, -0.01671934500336647, -0.002039626007899642, 0.013448492623865604, -0.003563291858881712, -0.021711306646466255, 0.014282969757914543, 0.004556096158921719, 0.005692325998097658, 0.015616643242537975, 0.04038273170590401, -0.0385945662856102, -0.0023171640932559967, 0.017225991934537888, -0.021756010130047798, -0.02266499400138855, 0.01677895151078701, 0.06198972836136818, -0.00590839609503746, 0.031322695314884186, 0.015072743408381939, -0.011101526208221912, -0.026479747146368027, 0.017240893095731735, -0.04172385483980179, -0.03472020849585533, 0.0033043804578483105, 0.03173993527889252, -0.011503863148391247, 0.028521236032247543, -0.004239441826939583, 0.014506490901112556, 0.034690406173467636, -0.0104160625487566, 0.01630210690200329, -0.007823223248124123, -0.026569155976176262, -0.0180604699999094, -0.007875378243625164, -0.019431395456194878, -0.023365359753370285, -0.0011567194014787674, 0.010460766963660717, -0.009596486575901508, -0.005427826661616564, 0.01381357666105032, -0.009201600216329098, -0.024229640141129494, -0.014797067269682884, -0.0025015687569975853, 0.01555703766644001, -0.02156229317188263, 0.007279322948306799, 0.00621387455612421, 0.0195953119546175, 0.004749814048409462, -0.003177718725055456, 0.0016307694604620337, 0.026196621358394623, 0.02278420515358448, -0.014692758210003376, -0.03698521852493286, -0.0199082400649786, 0.04038273170590401, 0.03847535699605942, -0.03546527773141861, 0.012196777388453484, 0.024289244785904884, 0.030845850706100464, 0.010512921959161758, -0.008620446547865868, 0.03331948071718216, 0.011556018143892288, 0.02431904710829258, 0.010505471378564835, -0.0005415719351731241, -0.016317008063197136, -0.013523000292479992, 0.021145055070519447, -0.0007641612319275737, -0.005405474454164505, 0.029057685285806656, -0.010050979442894459, -0.052572060376405716, -0.042528532445430756, -0.003829654073342681, -0.0007995520136319101, 0.007588526234030724, 0.021606996655464172, -0.01746441423892975, -0.023812400177121162, -0.015065292827785015, 0.016942866146564484, -0.045479003340005875, -0.014245716854929924, -0.011854046024382114, 0.003492510411888361, -0.004243167117238045, 0.018462806940078735, 0.01630210690200329, -0.009112192317843437, 0.04276695474982262, 0.04848908260464668, 0.023231247439980507, -0.07242069393396378, -0.005003137513995171, 0.017345203086733818, 0.00502176396548748, 0.004831771831959486, -0.022694798186421394, -0.03603152930736542, 0.007525195367634296, 0.013880632817745209, 0.006221325136721134, 0.02045959047973156, 0.005178228486329317, -0.030398810282349586, -0.044733934104442596, -0.04604525491595268, 0.01782204769551754, 0.007704012095928192, 0.0247958917170763, -0.027701660990715027, 0.004667856264859438, 0.0010104996617883444, -0.015571939758956432, -0.05841339752078056, 0.015646446496248245, -0.014029646292328835, -0.019133368507027626, 0.005062743090093136, 0.008680052123963833, -0.04667111486196518, -0.014841771684587002, -0.0049211797304451466, 0.05108192190527916, 0.004801969043910503, 0.0006915170233696699, -0.007577350363135338, -0.028700051829218864, -0.032365791499614716, 0.01004352793097496, 0.017240893095731735, -0.01971452310681343, -0.01916317082941532, 0.014811969362199306, -0.030845850706100464, -0.005059017799794674, 0.03454139083623886, 0.014059449546039104, -0.022873613983392715, 0.0005015244823880494, -0.04929375648498535, 0.024602174758911133, -0.0033285950776189566, 0.020161563530564308, 0.022441474720835686, 0.016078585758805275, 0.0018980628810822964, 0.023842204362154007, 0.0014156308025121689, 0.0037905378267169, -0.020444689318537712, -0.02670326828956604, -0.01099721621721983, 0.013113211840391159, -0.012964198365807533, -0.033289678394794464, -0.01399984396994114, 0.017166387289762497, 0.011079174466431141, -0.03325987234711647, 0.022635191679000854, 0.00453374395146966, 0.020072154700756073, -0.019133368507027626, -0.024050822481513023, -0.02254578471183777, 0.014342575334012508, -0.01585506461560726, -0.008612995967268944, -0.021964630112051964, -0.04273714870214462, 0.00451511749997735, 0.006806204095482826, 0.04214109480381012, 0.07093055546283722, 0.003963766153901815, 0.026628760620951653, -0.015780558809638023, -0.009872162714600563, -0.04813144728541374, -0.00595682580024004, 0.024289244785904884, 0.015318616293370724, 0.026539353653788567, 0.029102390632033348, -0.0075214700773358345, -0.015542136505246162, 0.016063684597611427, 0.003317419206723571, 0.015422925353050232, -0.044733934104442596, -0.05748951435089111, 0.03504803776741028, 0.017136583104729652, 0.01014038734138012, -0.01904395967721939, 0.00586369214579463, -0.033289678394794464, 0.009745500981807709, -0.021085448563098907, -0.006228775717318058, 0.01862672157585621, 0.035673897713422775, -0.044257089495658875, -0.03221677616238594, 0.0009667268604971468, -0.023544175550341606, 0.008627897128462791, 0.04047214239835739, -0.004541194532066584, -0.0020060979295521975, -0.02217325009405613, -0.06586408615112305, 0.00142401282209903, -0.034273166209459305, -0.026539353653788567, -0.015378221869468689, 0.006206423509865999, 0.012137171812355518, 0.04178346320986748, -0.015691149979829788, -0.0076034278608858585, 0.029862361028790474, -0.019625114277005196, -0.015452728606760502, 0.01916317082941532, -0.0009685895056463778, -0.004686483182013035, 0.013448492623865604, -0.005673699546605349, -0.02780597098171711, -0.031382299959659576, -0.02859574370086193, 0.005152150988578796, 0.008717305958271027, 0.010036077350378036, -0.036895811557769775, -0.010594879277050495, -0.015959374606609344, -0.0016754736425355077, 0.004030822776257992, -0.0009508941438980401, 0.008151053451001644, 0.00779342046007514, 0.0300113745033741, 0.013761421665549278, -0.01685345731675625, -0.0017155210953205824, -0.01721109077334404, 0.0008987393230199814, 0.022396769374608994, -0.03287243843078613, -0.025257835164666176, -0.009626289829611778, -0.005640171468257904, 0.02799968793988228, 0.005975452251732349, 0.02577938325703144, 0.018283989280462265, 0.01905886083841324, 0.0005392435705289245, -0.0076891109347343445, 0.013068508356809616, -0.008843967691063881, 0.032425396144390106, 0.025019412860274315, -0.0033230071421712637, 0.04127681627869606, -0.013150465674698353, 0.007882828824222088, -0.012934395112097263, 0.03466060385107994, 0.003157229395583272, -0.01579545997083187, -0.011690130457282066, -0.010885456576943398, -0.01420846302062273, -0.022098742425441742, -0.036299753934144974, 0.05909886211156845, 0.016689542680978775, -0.02284381166100502, 0.007651857100427151, 0.02969844453036785, -0.002598427701741457, 0.0008344771340489388, -0.0026394063606858253, -0.03680640086531639, 0.01016273908317089, 0.019610213115811348, 0.016734246164560318, 0.013373985886573792, 0.006545430049300194, 0.013284577988088131, 0.04312458634376526, 0.020981138572096825, 0.013835928402841091, 0.006854633800685406, 0.029236502945423126, -0.015631545335054398, 0.003915336914360523, 0.00744323804974556, 0.043392810970544815, 0.00430277269333601, 0.007260696031153202, 0.01892474852502346, -0.01862672157585621, -0.0060462336987257, -0.014163759537041187, -0.030279599130153656, 0.008843967691063881, 0.003539077006280422, -0.004179836250841618, 0.001991196535527706, 0.01215952355

### Amazon Data

##### 1. Create list of the Embedded data

In [ ]:
# The description field is part of the pay that will be embedded, 
# we use payload to store the other metadata fields that we want to be able to retrieve when we query the vector database.

pointstructs=[] # List of PointStruct objects to be stored in Qdrant; each PointStruct represents an embedded item with its metadata.

for i,data in enumerate(data_to_embed):
    embedding = get_embedding(data["description"]) # Embed description of each item
    pointstructs.append(
        PointStruct(
        id = i, 
        vector = embedding, 
        payload = data # Store the original data (description, image, rating_number, price, average_rating, parent_asin) as metadata
                    )
                       )

In [27]:
pointstructs

[PointStruct(id=0, vector=[0.026413757354021072, -0.01664472371339798, -0.042236387729644775, -0.0044387709349393845, 0.00407843803986907, -0.0122993728145957, -0.010180080309510231, 0.0013172179460525513, 0.044200871139764786, 0.002767892787232995, -0.03698353096842766, -0.010543081909418106, -0.05628671497106552, 0.05269939452409744, 0.04078437760472298, -0.0037394578102976084, -0.03852095082402229, 0.004468131344765425, -0.06610912829637527, 0.014947154559195042, 0.032264500856399536, 0.05385246127843857, 0.031922850757837296, 0.002129969419911504, 0.06730490177869797, -0.019997157156467438, 0.0003573303984012455, -0.02718246728181839, 0.019239123910665512, 0.0017162535805255175, 0.05111926794052124, -0.027054348960518837, 0.02190825715661049, -0.08558313548564911, -0.01193637028336525, 0.012897258624434471, -0.028335534036159515, -0.007137266453355551, -0.030897904187440872, 0.0055998447351157665, 0.02102210558950901, 0.02190825715661049, 0.0849425420165062, 0.03691947087645531, 0.02034948393702507, -0.011253071948885918, -0.0067155431024730206, 0.03179473429918289, -0.010473684407770634, 0.05035055801272392, -0.03162390738725662, 0.01945265382528305, 0.021321048960089684, 0.032883740961551666, 0.0021179583854973316, -0.0005198139697313309, 0.06376028805971146, 0.006144348066300154, 0.032755620777606964, 0.008055448532104492, -0.026990290731191635, -0.018021997064352036, 0.01850244216620922, 0.053169164806604385, -0.0021379769314080477, -0.03279832750558853, -0.013890177011489868, -0.01039361022412777, -0.0342930443584919, -0.05440764129161835, -0.01373002864420414, -0.010094667784869671, -0.011669456958770752, -0.03352433070540428, -0.012993347831070423, 0.04076302424073219, -0.0015027228510007262, -0.06632266193628311, 0.010890069417655468, 0.021545255556702614, -0.05521905794739723, 0.025965342298150063, -0.0358731709420681, 0.013495145365595818, 0.022399378940463066, 0.005036657210439444, -0.08169687539339066, -0.0033817936200648546, -0.052656691521406174, 0.04225774109363556, 0.03476281091570854, -0.003864907193928957, 0.05948967486619949, -0.023531092330813408, -0.001293863053433597, 0.02696893736720085, -0.004518845118582249, -0.012897258624434471, -0.002877327147871256, 0.02180149219930172, 0.005994876381009817, -0.010858040302991867, -0.016858255490660667, 0.0035312653053551912, -0.011840282008051872, 0.034784164279699326, -0.033994100987911224, 0.0026744729839265347, 0.019975803792476654, 0.032136380672454834, -0.03576640412211418, -0.0050419955514371395, -0.007521621882915497, 0.012395462021231651, 0.0028533050790429115, -0.05141821131110191, 0.03322538733482361, -0.012491550296545029, -0.030022427439689636, -0.032093677669763565, -0.008306346833705902, 0.04249262437224388, 0.04898396134376526, -0.049069371074438095, -0.027609528973698616, 0.015235421247780323, -0.021790815517306328, 0.03683405742049217, -0.01370867621153593, -0.026584582403302193, -0.02028542384505272, -0.020157305523753166, 0.028057944029569626, -0.007345458958297968, -0.0008728070533834398, 0.03542475774884224, 0.00834905356168747, -0.040955204516649246, 0.029787544161081314, 0.0015480981674045324, -0.019495360553264618, 0.0337592177093029, 0.017904555425047874, 0.05825119465589523, -0.035446107387542725, 0.054621171206235886, -0.02545286901295185, 0.01400761865079403, -0.0076177106238901615, 0.05931885167956352, 0.03843554109334946, -0.01721058040857315, -0.043581631034612656, -0.015737218782305717, -0.03168796747922897, -0.027502764016389847, 0.02773764729499817, 0.005695933476090431, -0.03557422757148743, -0.008439804427325726, 0.016890283674001694, -0.040997911244630814, -0.0223566722124815, 0.008418451063334942, -0.02880530245602131, 0.0449695810675621, 0.017509523779153824, 0.05180256813764572, -0.06867149472236633, 0.02186555229127407, 0.009817077778279781, 0.022719675675034523, 0.009454075247049332, 0.0019151042215526104, 0.06077085807919502, 0.014509416185319424, 0.05035055801272392, 0.002023204229772091, -0.029125597327947617, 0.05171715468168259, -0.046208061277866364, -0.003437845502048731, 0.005220827646553516, -0.0074522243812680244, -0.007815226912498474, -0.011413220316171646, 0.025132572278380394, -0.025367455556988716, -0.0024489311035722494, -0.01776576042175293, -0.029104245826601982, 0.008290332742035389, -0.030022427439689636, 0.04270615428686142, -0.04625076800584793, 0.004030393436551094, 0.0024916373658925295, 0.006085627246648073, -0.012961317785084248, -0.04353892430663109, -0.008792129345238209, 0.0425993911921978, 0.001652194419875741, -0.021993670612573624, 0.0033978084102272987, -0.012843876145780087, -0.0051434226334095, 0.06649348139762878, 0.026413757354021072, 0.034335747361183167, 0.036855410784482956, -0.0011090254411101341, -0.010671200230717659, -0.0157585721462965, 0.05743977800011635, -0.01692231371998787, 0.01538489293307066, -0.01731734536588192, 0.015673158690333366, 0.02449198067188263, -0.0337592177093029, 0.004740383476018906, 0.04321863129734993, -0.03514716774225235, 0.038093890994787216, -0.0029867617413401604, -0.03412221744656563, -0.02573045901954174, -0.012075165286660194, -0.0644862949848175, 0.03177338093519211, 0.01398626621812582, -0.020210688933730125, 0.03749600425362587, 0.03980213776230812, 0.027331938967108727, 0.001073659397661686, -0.018342293798923492, 0.01462685875594616, -0.0031575863249599934, 0.019260475412011147, 0.0138154411688447, -0.024342508986592293, 0.020595043897628784, 0.02410762570798397, 0.0017015733756124973, 0.0068383230827748775, 0.011872311122715473, -0.045097701251506805, 0.03207232430577278, 0.031816087663173676, 0.04607994109392166, -0.02321079559624195, -0.032478030771017075, 0.0035072430036962032, 0.01558774709701538, -0.07153280824422836, -0.028292827308177948, -0.01219260785728693, -0.05440764129161835, -0.02886936068534851, -0.014456033706665039, -0.0035392725840210915, -0.025303397327661514, 0.0656820684671402, -0.011242395266890526, -0.02897612750530243, -0.0009688959107734263, -0.0064966739155352116, 0.006747572682797909, 0.046378884464502335, -0.04200150445103645, -0.003512581344693899, 0.0627780482172966, 0.01899356208741665, -0.018705295398831367, -0.03681270778179169, 0.010046622715890408, -0.011274425312876701, -0.005866758059710264, 0.006897043902426958, -6.5268686739727855e-06, -0.0026437779888510704, -0.009320618584752083, -0.05269939452409744, -0.0021139546297490597, 0.0047804201021790504, -0.01995445042848587, -0.015491657890379429, 0.002322147134691477, 0.03826471418142319, -0.015876013785600662, 0.03104737587273121, -0.02831418067216873, -0.02696893736720085, -0.0365351177752018, -0.07392435520887375, 0.05056408792734146, -0.029467247426509857, -0.0494537279009819, 0.017957938835024834, 0.03207232430577278, -0.010729921981692314, 0.003982348833233118, -0.02006121724843979, 0.05991673469543457, -0.012320726178586483, 0.019762273877859116, -0.049795377999544144, -0.01034556608647108, -0.01781914383172989, -0.0007600361132062972, 0.02600804902613163, 0.005877434741705656, -0.014765653759241104, -0.027887118980288506, -0.02876259572803974, 0.005962846800684929, -0.0002684148494154215, -0.03593723103404045, 0.08186770230531693, 0.005685256794095039, -0.04885584115982056, 0.016281722113490105, 0.026776758953928947, 0.033994100987911224, 0.02397950552403927, -0.017744407057762146, -0.03610805422067642, -0.03610805422067642, 0.034335747361183167, -0.055688828229904175, -0.003456529462710023, -0.012331402860581875, 0.02818606235086918, -0.01748817041516304, -0.029552659019827843, -0.011872311122715473, -0.0009789051255211234, 0.03559558093547821, 0.001670878380537033, -0.019324535503983498, -0.056585654616355896, 0.008861526846885681, 0.017178550362586975, -0.05099115148186684, 0.053553517907857895, -0.041617147624492645, 0.038243360817432404, -0.023744622245430946, -0.013217555359005928, -0.01068187691271305, 0.011722839437425137, -0.0030267988331615925, -0.04556746780872345, -0.03922560438513756, 0.018342293798923492, -0.002375529846176505, -0.023958154022693634, 0.0449695810675621, 0.01558774709701538, 0.0072707231156528, 0.03538205102086067, -0.046165354549884796, 0.060343798249959946, 0.0122993728145957, -0.026712700724601746, 0.05205880478024483, 0.01944197714328766, 0.02780170738697052, 0.0030321369413286448, 0.019644832238554955, -0.0007733817910775542, -0.04031461104750633, -0.018513118848204613, -0.04808713123202324, -0.005984200164675713, -0.02769494242966175, -0.02790847234427929, -0.02046692557632923, -0.024022212252020836, 0.031367670744657516, 0.009619561955332756, 0.033716510981321335, 0.009096411056816578, -0.00980640109628439, -0.007089221850037575, 0.013697999529540539, -0.018513118848204613, 0.02158796228468418, 0.0015894697280600667, -0.030705725774168968, -0.002922702580690384, -0.0035579565446823835, 0.07682837545871735, 0.06653618812561035, 0.03826471418142319, 0.04573829099535942, 0.01185095775872469, -0.01603616215288639, 0.01353785116225481, -0.012096518650650978, 0.028783949092030525, 0.003416492370888591, -0.024406567215919495, 0.00663013057783246, -0.00032196438405662775, 0.007553651463240385, -0.0046042571775615215, 0.004921884275972843, 0.032478030771017075, -0.10796116292476654, 0.009534149430692196, 0.00475105969235301, -0.036620527505874634, -0.027993885800242424, -0.048514191061258316, 0.026990290731191635, -0.004062423016875982, 0.010067976079881191, -0.013890177011489868, -0.009320618584752083, -0.04200150445103645, 0.00044541186071000993, -0.039545901119709015, 0.027545470744371414, 0.0064966739155352116, -0.07998862862586975, 0.032136380672454834, -0.017125168815255165, 0.0013499149354174733, -0.04859960451722145, 0.024406567215919495, 0.03482687100768089, 0.0013352346140891314, -0.043239980936050415, -0.019815655425190926, 0.01521406788378954, 0.04514040797948837, -0.002355511300265789, 0.02001851052045822, 0.04249262437224388, -0.013516497798264027, -0.05205880478024483, -0.02321079559624195, 0.02383003570139408, 0.010740597732365131, 0.06995268166065216, 0.017445463687181473, 0.021652020514011383, -0.00326435174793005, 0.02365921065211296, -0.0066247922368347645, 0.02438521571457386, 0.005888111423701048, 0.005653227213770151, -0.011519985273480415, -0.05312645807862282, 0.0018790708854794502, 0.03542475774884224, 0.03815795108675957, 0.022655615583062172, -0.03232856094837189, 0.015555717051029205, 0.03256344422698021, -0.02573045901954174, 0.044585227966308594, 0.010943452827632427, -0.01580127701163292, -0.04949643462896347, -0.0007159953820519149, 0.020050540566444397, -0.008471833541989326, 0.04291968792676926, 0.023338913917541504, -0.0007840582984499633, 0.026926230639219284, -0.018000643700361252, -0.019420623779296875, 0.02073383890092373, -0.0003254676121287048, 0.0032056306954473257, -0.04590911790728569, -0.020146628841757774, 0.007324105594307184, 0.05398058146238327, -0.009363324381411076, -0.030449489131569862, -0.010500376112759113, 0.019377918913960457, -0.013751382008194923, -0.017947262153029442, 0.03980213776230812, -0.007580342702567577, -0.016324428841471672, -0.024897688999772072, -0.05150362476706505, -0.010003916919231415, 0.002920033410191536, 0.002917364239692688, 0.03728247433900833, -0.03322538733482361, -0.048514191061258316, -0.0017816474428400397, 0.07550448179244995, -0.016004132106900215, -0.0006656154873780906, -0.0022193854674696922, -0.041168734431266785, 0.004772413056343794, 0.001999181928113103, 0.025196632370352745, -0.005159437656402588, -0.023851387202739716, -0.0321790874004364, -0.0238727405667305, 0.009704973548650742, 0.00941670686006546, 0.014274532906711102, 0.00017699699674267322, 0.001123705762438476, 0.023232148960232735, 0.028228769078850746, -0.028997479006648064, 0.0032349913381040096, -0.007142604328691959, -0.019046945497393608, -0.05483470484614372, -0.041339557617902756, -0.02814335748553276, -0.0036140084266662598, -0.034100864082574844, -0.0009315280476585031, -0.008808144368231297, -0.002575715072453022, 0.00145334389526397, 0.03414357081055641, -0.03324674069881439, -0.044030047953128815, -0.025580987334251404, 0.030086487531661987, -0.025196632370352745, 0.026883525773882866, -0.030791137367486954, 0.006187054328620434, 0.007548313122242689, 0.01686893217265606, -0.03198691084980965, -0.003493897384032607, -0.02207908220589161, 0.023168088868260384, -0.02303997054696083, 0.0024075594265013933, -0.027609528973698616, -0.01793658547103405, -0.0009935854468494654, -0.007260046433657408, 0.010281506925821304, 0.032136380672454834, 0.024363862350583076, 0.024299802258610725, 0.003998363856226206, 0.004556213039904833, -0.0017029079608619213, -0.0027545469347387552, 0.013569881208240986, -0.00015581073239445686, 0.002017865888774395, -0.049795377999544144, -0.008429127745330334, -0.05504823476076126, -0.004508168436586857, 0.008258302696049213, 0.031538497656583786, 0.022826440632343292, 0.02410762570798397, 0.009785047732293606, -0.00403573177754879, -0.009069719351828098, 0.047275714576244354, 0.010724583640694618, 0.008557246066629887, 0.0008467829902656376, 0.004137158859521151, -0.009827754460275173, -0.000740017625503242, -0.020360160619020462, 0.00732944393530488, -0.0037287811283022165, 0.020765868946909904, 0.013943559490144253, 0.02415033057332039, -0.04522581771016121, 0.0028639815282076597, -0.011776222847402096, 0.03025731071829796, 0.018513118848204613, -0.009961211122572422, 0.021929610520601273, -0.0597459115087986, 0.015630453824996948, -0.018203498795628548, -0.002052564639598131, 0.056414831429719925, -0.03234991431236267, -0.0013559204526245594, 0.043069157749414444, -0.005583829712122679, -0.02573045901954174, -0.0022394040133804083, -0.03621482104063034, 0.017456140369176865, -0.019409947097301483, -0.008594613522291183, -0.02157728560268879, 0.0366632342338562, 0.0056051830761134624, 0.0017949930625036359, 0.02007189393043518, -0.02331756055355072, -0.05385246127843857, -0.025196632370352745, 0.011786898598074913, 0.020274747163057327, 0.023637857288122177, 0.014018295332789421, 6.0138940170872957e-05, -0.02886936068534851, -0.03681270778179169, -0.027865765616297722, 0.004011709708720446, 0.02393680065870285, 0.003624684875831008, -0.02056301385164261, -0.012224636971950531, -0.0009849107591435313, 0.012000429444015026, 0.0036433688364923, 0.02342432551085949, -0.07430870831012726, 0.0051647755317389965, -0.0023061323445290327, 0.013601910322904587, -0.04804442450404167, -0.0050873709842562675, 0.01665540039539337, 0.025068514049053192, -0.010137373581528664, -0.009929181076586246, -0.009000321850180626, 0.02797253243625164, -0.01400761865079403, 0.005033988039940596, 0.005477064289152622, 0.008172890171408653, 0.031196847558021545, -0.012544932775199413, 0.0410192608833313, -0.012907935306429863, 0.005994876381009817, -0.014317238703370094, -0.016965020447969437, -0.022997265681624413, 0.025303397327661514, -0.030897904187440872, -0.005287555977702141, -0.004753728862851858, -0.0005631874082610011, 0.016900960355997086, -0.04847148805856705, 0.07213069498538971, -7.932334847282618e-05, -0.0039743417873978615, 0.04136091098189354, -0.010826010257005692, 0.023509738966822624, 0.011893664486706257, -0.00365671468898654, 0.0026624619495123625, 0.019474007189273834, 0.03269156068563461, 0.03160255402326584, -0.026990290731191635, 0.007249369751662016, -0.015406245365738869, 0.04125414788722992, -0.025794517248868942, 0.0022794411052018404, 0.01485106535255909, -0.04505499452352524, 0.016004132106900215, 0.010751274414360523, 0.03143173083662987, 0.011167659424245358, -0.03911883756518364, -0.033097270876169205, -0.0004440773045644164, 0.010799319483339787, 0.029851602390408516, -0.03134631738066673, 0.013121466152369976, 0.028570417314767838, -0.020530983805656433, 0.01586533710360527, -0.019687537103891373, -0.02673405408859253, -0.008674687705934048, -0.020135952159762383, 0.00834905356168747, -0.009005660191178322, 0.009688959456980228, 0.011872311122715473, -0.020274747163057327, -0.03995160758495331, -0.004804442636668682, 0.00014930471661500633, 0.008445141837000847, 0.029723484069108963, -0.0015240759821608663, -0.03083384409546852, 0.019377918913960457, 0.006245775148272514, -0.019879715517163277, 0.02696893736720085, 0.02728923410177231, -0.015555717051029205, 0.04018649086356163, -0.0010329551296308637, 0.01277981698513031, 0.02063775062561035, 0.03249938413500786, -0.027823060750961304, 0.014253179542720318, 0.002922702580690384, -0.004131820518523455, 0.0008554576779715717, -0.016377810388803482, -0.06038650497794151, 0.012843876145780087, -0.029744837433099747, -0.0028239444363862276, -0.017413435503840446, -0.0253888089209795, 0.021886905655264854, 0.01409303117543459, 0.02886936068534851, -0.027865765616297722, -0.009331295266747475, -0.025367455556988716, -0.008135522715747356, -0.018417028710246086, 0.004369373433291912, 0.03459198772907257, 0.009651591069996357, -0.025538280606269836, -0.04063490778207779, -0.012641021981835365, -0.013911530375480652, -0.007190648932009935, -0.0005108056357130408, 0.02472686395049095, -0.020146628841757774, 0.008541231043636799, 0.017626965418457985, 0.01210719533264637, -0.012555609457194805, -0.053382694721221924, -0.015160685405135155, -0.053895168006420135, -0.006603439338505268, 0.08899962902069092, -0.03482687100768089, 0.01721058040857315, 0.010633832775056362, -0.010660524480044842, -0.03384462743997574, -0.05833660811185837, 0.00766575476154685, 0.004169188439846039, 0.04176662117242813, 0.057311661541461945, 0.000915513199288398, 0.031581200659275055, 0.016548635438084602, 0.016794195398688316, -0.05150362476706505, 0.001645521610043943, 0.022036375477910042, 0.0231467355042696, 0.006651483941823244, 0.000540833396371454, -0.029168304055929184, -0.007265384774655104, -0.009945196099579334, -0.0020498954690992832, 0.015769248828291893, 0.0064966739155352116, -0.04970996454358101, 0.026776758953928947, -0.007687108125537634, 0.014562798663973808, -0.023680564016103745, 0.03779494762420654, -0.0493256114423275, 0.0005258195451460779, -0.018288910388946533, -0.05483470484614372, -0.007500268518924713, -0.03179473429918289, 0.0032269838266074657, -0.019185740500688553, -0.01670878380537033, 0.004460124298930168, 0.05470658466219902, -0.00910708773881197, 0.04264209792017937, 0.009010998532176018, 0.010943452827632427, -0.02790847234427929, 0.014039648696780205, 0.04514040797948837, -0.04757465794682503, 0.008840174414217472, -0.01400761865079403, -0.014989860355854034, -0.021150223910808563, -0.021054135635495186, 0.005978861823678017, -0.025367455556988716, -0.00792733021080494, -0.02101142890751362, -0.006651483941823244, 0.008653334341943264, -0.036065347492694855, -0.005036657210439444, 0.011979077011346817, -0.014797682873904705, -0.017338698729872704, -0.017755083739757538, -0.017114492133259773, -0.015662482008337975, 0.011669456958770752, -0.020552337169647217, 0.01353785116225481, 0.00731342937797308, -0.003130895085632801, 0.015577070415019989, -0.02549557574093342, -0.0018376992084085941, 0.01867326721549034, -0.002379533601924777, -0.0008494521025568247, -0.0053863138891756535, 0.022847793996334076, -0.029552659019827843, 0.002738532144576311, 0.01777643710374832, -0.037645477801561356, 0.0021353077609091997, 0.009064381942152977, -0.008429127745330334, -0.03457063436508179, 0.009187161922454834, -0.014616182073950768, 0.013601910322904587, 0.007703122682869434, 0.03004378080368042, -0.0018844091100618243, 0.01665540039539337, 0.016110897064208984, -0.010158726945519447, -0.00030094492831267416, -0.0395672544836998, -0.024641452357172966, -0.011509308591485023, 0.015683835372328758, 0.022463437169790268, 0.010222786106169224, -0.006747572682797909, 0.010222786106169224, 0.009699635207653046, 0.007484253961592913, 0.020328130573034286, -0.021331725642085075, -0.03328944742679596, -0.009240544401109219, -0.0491974912583828, 0.02970213070511818, 0.03928966447710991, -0.026648640632629395, -0.007099898532032967, -0.003859568852931261, -0.00790063850581646, -0.01400761865079403, -0.01665540039539337, 0.00042706154636107385, -0.006827646400779486, 0.0

##### 2. Write to Qdrant

In [28]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-00",
    wait=True, # Wait for the operation to complete before proceeding; ensures that the points are fully indexed and available for search immediately after upsert.
    points=pointstructs, # List of PointStruct objects to be upserted into the Qdrant collection
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

##### 3. Retrieval function

In [32]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query) # Embed the query using the same embedding model
    result = qdrant_client.query_points(  # Query the Qdrant collection for the top k most similar points to the query embedding
        collection_name="Amazon-items-collection-00",
        query=query_embedding,
        limit=k
    )
    return result

##### 4. Test Retrieval

In [33]:
retrieve_data("What kind of charging cords do you offer?", k=10).points # Returns top10 most similar items to the query based on cosine similarity of their embeddings as a list.

[ScoredPoint(id=14, version=1, score=0.43398994, payload={'description': "iPhone Charger Cord [Apple MFi Certified] Lightning Cable 1m/3.3FT Fast Charging High Speed Data Sync USB Cable Compatible with iPhone 14/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S iPad[Fast Charging & Sync] - iPhone Charger Cord Max 2.4 output current, high quality copper wire, improve charging and data transfer speed of iPhone charging cable. iPhone Lightning Cable ensures faster charging time and keeps your device safer. [Perfect comptibility] - iPhone lightning cables compatible with iPhone 14/14 Plus/14 Pro/14 Pro Max/iPhone 13/13 mini/13 Pro/13 Pro Max/12/12 mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/SE 2/XS/XS Max/XR/X/8Plus/8/7Plus/7/6s Plus/6s/6 Plus/6/5s/5c,iPad,AirPods [MFi Certified] - The lightning cable has an original lightning chip inside. Make sure it's compatible with your iPhone and charges your device safely. Enjoy fast data transfer, sync and charging. [Superior Durability] - iPhone lightning cable are made of top quality materials and coated with premium TPE. Passed 10,000 flex tests and won't get tangled for extra protection and durability. [What you get?] - 1x 3ft Mfi Certified iPhone Charging Cable. If you have any quality problems with our products, please feel free to contact us. We provide 24/7 customer support", 'image': 'https://m.media-amazon.com/images/I/31CSP4L973L.jpg', 'rating_number': 119, 'price': 4.99, 'average_rating': 4.4, 'parent_asin': 'B0BN1CMWCP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.42853904, payload={'description': 'iPhone Charger, [Apple MFi Certified] 2 Pack iPhone Charger Data Sync Transfer Lightning Cable with Travel USB Wall Charger Block Compatible with iPhone 13/12/11 Pro/SE/XS/X/XR/8/7/iPad/AirPods[2-Pack iPhone Charger Block and 2-Pack Lightning Cable] Apple iPhone charger compatible with iPhone 14/14Plus/14 Pro/14 ProMax/13/13 Mini/13 Pro/13 Pro Max/12/12 Mini/12 Pro/12 Pro Max/11/11 Pro/11 Pro Max/X/XR/XS/XS Max/8/8 Plus/7/7 Plus/6s/6s Plus/6/6 Plus/5/5S/5C/SE, iPad, Air Pods. [MFi Certified Lightning Cable] iPhone chargers USB to lightning cable with the original MFi Chip, which automatically provides multiple charging protection measures, provides Apple iPhone charger over-voltage protection, overheat protection, battery protection and automatic chip identification function, thoroughly protect your apple device from damages. [Mini iPhone Charger Block] Small, Stylish and lightweight 5W Apple iPhone charger travel wall charger block is easy to carry and saves in-bag space. Apple chargers for iPhone is perfect for home, office and travel. [Safe Charging and Efficient Data Sync] Apple iPhone charger cable built-in smart chip can automatically detect iPhone device without pop-up warning message. Lightning cable also can identify the appropriate current to keep your iPhone charging at maximum speed. Advanced protection measures to ensure the safety of your Apple device. In addition, you can enjoy the data transfer speed of up to 480Mbps. [What You Get] 2-Pack USB Apple iPhone Charger Block and 2-Pack 3 FT Lightning Cable. If you have any questions, please feel free to contact us.', 'image': 'https://m.media-amazon.com/images/I/41LMYBn5EQL.jpg', 'rating_number': 169, 'price': 11.99, 'average_rating': 4.4, 'parent_asin': 'B0B14SR88S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=1, score=0.39657325, payload={'description': 'NVK USB Charger Cable 2 in 1 for Dog Training Collar and Remote, 2.6Ft USB Magnetic Charging and Micro USB Cable【USB 2-In-1 Charger】: This 2 in 1 dog collar charger can charge the nvk shock collars for dog and remote at the same time, which can save your time. The length of charging cable is 2.6ft 【Fast Charger for E-collar】: The dual charger ensures that your bark collar and remote syncing and charging at the same time. NVK Charger Cable 2 in 1 provides a much faster charging and data exchange than other regular cables, protects your e-collar and remote from damage 【Convenient Design】: Lightweight and slim design, you could put the nvk charging cable in your bag or pockets, convenient to take out , expecially fits for the outside back up charging cord in car or traveling 【Wide Compatibility】: USB charger cable for electric dog collar works with power bank, wall charger, car charger, laptop and PC USB port. It can be a good choice as a shock collar charger replacement when your charging cable was damaged or missing 【What You Get】: 2.6Ft NVK dog collar and remote charger with USB micro and magnetic port, 12-month warranty, friendly customer service and 24 hours prompt reply. Note: When charging the devices at the same time, the display on the NVK remote control will show the charging status of the remote control, but not the charging status of the collar, and the red light on the collar will turn green when charging is completed. The charging plug is NOT included', 'image': 'https://m.media-amazon.com/images/I/419CQJ0W07L._AC_.jpg', 'rating_number': 232, 'price': 19.99, 'average_rating': 4.5, 'parent_asin': 'B09WTM6SP3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=13, version=1, score=0.3258348, payload={'description': '[Apple MFi Certified] 2PACK Lightning to 3.5 mm Adapter，iPhone Aux Adapter Support 2 in 1 Audio + Charger iPhone Splitter Compatible with iPhone 14/13/12/11/X/XR/XS/8/7/6/iPad/iPod【2 in 1 Audio and Charging Function】: The iPhone headphone adapter supports listening to music and charging your phone at the same time.Perfect for gaming and music lovers. 【Supper Compatibility】iPhone lightning to 3.5mm adapter Compatible with iPhone 13/12/11/XS/XR/X/8/7/6/se/iPad/iPod Supports iOS 10/11/12/13/14 or later systems.No need to worry about system upgrades. 【Original HiFi Sound Quality】The iPhone Dongle supports up to 24-bit 48kHz lossless output, ensuring the stability and fidelity of sound transmission. 【Superior Charging Speed】Built in latest upgraded smart chip to ensure fast charging (up to 2.1A input,support 20w PD Charger). 【Service and Warranty】We provide 1 year worry-free service.If you have any questions about this iPhone adapter,Please contact us at any time.We will give you a satisfactory reply within 24 hours.', 'image': 'https://m.media-amazon.com/images/I/418RlB1+MtL._AC_.jpg', 'rating_number': 578, 'price': 11.99, 'average_rating': 3.8, 'parent_asin': 'B09Q5TQ2CL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=18, version=1, score=0.29179686, payload={'description': 'J-Tech Digital Silent Ergonomic Mouse Wireless & Bluetooth w/ 4-Way Scroll Wheel | Built-in Screen, DPI Adjustment, USB-C Rechargeable Battery, Multi-Device for Laptop, PC, Windows [V915]𝐁𝐮𝐢𝐥𝐭-𝐢𝐧 𝐎𝐋𝐄𝐃 𝐃𝐢𝐬𝐩𝐥𝐚𝐲 𝐈𝐧𝐟𝐨𝐫𝐦𝐚𝐭𝐢𝐨𝐧 𝐒𝐜𝐫𝐞𝐞𝐧 –Monitor key information about your mouse easily without having to install any software. Check the battery life, charging status, connection mode, and DPI at a glance via the built-in OLED display on the mouse. 𝐒𝐢𝐥𝐞𝐧𝐭 𝐂𝐥𝐢𝐜𝐤 & 𝟒-𝐖𝐚𝐲 𝐒𝐜𝐫𝐨𝐥𝐥 𝐖𝐡𝐞𝐞𝐥 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧 – Providing up to 92% less clicking noise than a traditional mouse, enjoy using your mouse while being distraction-free! Use the middle scroll wheel to go up/down and left/right while navigating through a page. This function provides extra convenience while browsing the web, or using excel etc. 𝐄𝐫𝐠𝐨𝐧𝐨𝐦𝐢𝐜 𝐃𝐞𝐬𝐢𝐠𝐧 𝐰/ 𝐌𝐮𝐥𝐭𝐢-𝐃𝐞𝐯𝐢𝐜𝐞 𝐂𝐨𝐦𝐩𝐚𝐭𝐢𝐛𝐢𝐥𝐢𝐭𝐲 – The ergonomic layout of the mouse, along with the attached palm rest, helps keep your wrist and arm in a comfortable position at all times. Supports wireless 2.4GHz, Bluetooth 1 & Bluetooth 2 simultaneous device connectivity (up to 3 devices), USB Wired and provides up to 10m/32ft. working range. 𝐑𝐞𝐜𝐡𝐚𝐫𝐠𝐞𝐚𝐛𝐥𝐞 𝐁𝐚𝐭𝐭𝐞𝐫𝐲 | 𝐀𝐝𝐣𝐮𝐬𝐭𝐚𝐛𝐥𝐞 𝐃𝐏𝐈 – With a built-in 1000mAh rechargeable lithium battery, enjoy continuous use of the mouse for days without having to charge again. Use the provided USB cable to charge the mouse when needed. Toggle between 5 levels of DPI settings to fit your needs (800/1200/1600/2400/4000). 𝐅𝐫𝐞𝐞 𝐋𝐢𝐟𝐞𝐭𝐢𝐦𝐞 𝐓𝐞𝐜𝐡𝐧𝐢𝐜𝐚𝐥 𝐒𝐮𝐩𝐩𝐨𝐫𝐭 – All J-Tech Digital products include a one-year manufacturer replacement warranty and free lifetime technical support from our customer support team located in Stafford, TX. Support is available from 9AM – 6PM CST, Mon – Fri. Contact information available on our seller page.', 'image': 'https://m.media-amazon.com/images/I/31p6JFnlFTL._AC_.jpg', 'rating_number': 3513, 'price': 39.99, 'average_rating': 4.3, 'parent_asin': 'B0BZBFDY5J'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=26, version=1, score=0.28726035, payload={'description': '2-Pack Upgraded Batteries Compatible with Ring-Doorbell-Spotlight Cam, Doorbell 1/2/3and 3Plus, Larger Capacity and Battery Life, Rechargeable Lithium Ion 3.65V Battery, Easy Release InstallationThe battery can be charged with any 5V USB ports like PC, car charger or power bank etc. Includes a quick-release tab to easily charge the battery without moving the device. The battery powers your Ring device for up to 6 months, depending on motion and light settings. The rechargeable battery is designed to power your device without being connected to an external power source. All Ring doorbell models that come with a battery, any hard-wired power source will charge the battery rather than the doorbell itself. Premium cells create quality batteries. 6040mAh high battery capacity for continuous surveillance. Features four layers of protection (over-charging, short-circuit, high-temperature, and surge protection) with a high-quality, fire-resistant construction, ensure complete protection for you and your devices.', 'image': 'https://m.media-amazon.com/images/I/41gDTFgBoHL._AC_.jpg', 'rating_number': 112, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B09XCV9C2H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=36, version=1, score=0.2821844, payload={'description': 'Compressed-air-duster-Keyboard-cleaner-110000RPM Electric air dusters-Replace air can-no Canned air Duster-pc Cleaning-air Blower-Cordless air Duster for Computers-Compressed air-car dusters 7600mAh…Air duster-【LED Lights & 3-Speed Wind】: Compressed air duster with an upgraded 1.85-2.51 OZ motor, which provides super airflow for deep cleaning. Press 3 seconds and hold the power on, click the button, you can has 3 speed wind speeds for different equipment cleaning, compressed air to clean more easy. pc duster【Strong Wind deep cleaning】air blower max speed is 110000RPM, powerful compressed air dusters is your good helper, used for deep cleaning of tiny dust, Stronger winds, sweeping away dust that worries you.Less energy consumption, longer life and noise relief while maintaining strong power. Compressed air duster【 5 nozzles and 3 brushes & Multi-use】air duster have【 5 】nozzles, 【3】 brushes for multi-scene cleaning, such as：pc, fans, lily windows,keyboards, cars, household cleaning and so on. Thin and long nozzle makes it easier to clean corners or place where hand cannot reach. Nozzle can be replaced, the brush with clean, more convenient. Electric air duster【type C charging 】：Compressed air dusters can be charged by computer, mobile power supply, car charger, adapter. Air duster is high technical configuration, with charging cable for use. Air duster【 Lifetime Warranty & Easy to Carry】The air duster is portable and easy to use, Provision of Product Services.If you have any questions, please contact us, we will do our best to solve the problem for you.', 'image': 'https://m.media-amazon.com/images/I/41CYv0QEV2L._AC_.jpg', 'rating_number': 915, 'price': 49.98, 'average_rating': 4.3, 'parent_asin': 'B0CGPXNPXN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42, version=1, score=0.2626785, payload={'description': '[2 Packs] USB C Headphones, Type C w/h Mic & Remote Control Noise Cancelling Headsets In Ear Headphone HiFi Stereo USB C Earphones Compatible with iPad Pro, Pixle, HTC, Samsung Galaxy S22/S21, OnePlus', 'image': 'https://m.media-amazon.com/images/I/31D1FmIFlxL._AC_.jpg', 'rating_number': 115, 'price': None, 'average_rating': 3.8, 'parent_asin': 'B09ZHNGQX3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=35, version=1, score=0.262169, payload={'description': 'surundo for Fitbit-Charge-5-Bands for Women Men, Breathable Sport Band Soft Silicone Waterproof Replacement Wristbands Strap for Fitbit Charge 5 Advanced Fitness Health/TrackerBuckle closure 【Compatible Models】Surundo 4-Pack Sport Fitbit Charge 5 Bands Compatible for Fitbit Charge 5 Activity Tracker ( Note: only for Fitbit Charge 5 bands for women men. NO tracker included ) Adopts a soft and breathable porous design. The strap is beautiful and ergonomic, it is very suitable for sports, keep the wrist dry, light and simple, very comfortable to wear. 【Fit Wrist Size】Our Charge 5 Sport Bnads Only One size of 130mm-220mm (5.1 - 8.7"), More ventilation holes will allow the air and liquid pass easily, very lightweight & comfortable to wear. 【Double Buckle & Fastener Notch】 Multi-holes design band with double metal buckle, keeps your charge 5 bands secure and stable, even during high-intensity workouts. And a strap holder with a notch to secure the extra length. Never worry about falling off. 【Breathable,Waterproof & Adjustable】Surundo charge 5 bands for men women are made of durable and flexible silicone. The Charge 5 Sport bands come with breathable holes, Eco-friendly, Waterproof, elastic, lightweight. Skin-friendly material, It will be best choice for sport, exercise or yoga. Great for wearing. 【Sport Bands for Charge 5 Accessories】Personalize your Fitbit Charge 5 Bands to match your mood and daily wear style. It is very suitable for running, swimming, cycling, fitness, gathering, climbing, hiking and more outdoor activities. you can change it according to different occasions and your moods & outfits in daily life. Give your Fitbit Charge 5 Activity Tracker a new look, let it always look more fashionable.', 'image': 'https://m.media-amazon.com/images/I/51JlX+4ZQrL._AC_.jpg', 'rating_number': 757, 'price': 9.99, 'average_rating': 4.6, 'parent_asin': 'B0B15P3H24'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=24, version=1, score=0.24665764, payload={'description': 'Earbuds/Earphones, Wired Earbud Headphones Noise Isolating, Pure Sound in-Ear Headphones with Microphone for iPhone,Android Phones,Laptops,PC,MP3 Player,iPad,Tablet,and all 3.5mm Headphone Jack device', 'image': 'https://m.media-amazon.com/images/I/41cCE34tLeL._AC_.jpg', 'rating_number': 121, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B0928NPMRH'}, vector=None, shard_key=None, order_value=None)]